<h2 >Výdaje - detail</h2>
<!--<hr>-->
<div class="col-lg-5">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Detail transakcie  <?php echo $this->vydaj['doklad_cislo'];?></h3>
        </div>
        <div class="panel-body">




            <!--        <div class="col-lg-6">-->
            <!--            id-->
            <!--            --><?php //echo $this->prijem['ts_prijmy_id']; // render the user name field here ?>
            <!--        </div>-->


            <div class="row">
                <fieldset>
                    <legend>Dátum výdaju</legend>

                    <div class="col-lg-6">
                        Dátum:
                        <?php echo date("d.m.Y", strtotime($this->vydaj['datum_vydaju_d'])); // render the user name field here ?>
                    </div>
                </fieldset>
            </div>
            <!---->
            <div class="row">
                <fieldset>
                    <legend>Sklady</legend>
                    <div class="col-lg-6">
                        Sklad:

                        <?php echo $this->ciselniky['skladyModel']->getNazov($this->vydaj['sklad_enum']); // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
                        Podsklad:
                        <?php echo $this->ciselniky['podskladyModel']->getNazov($this->vydaj['podsklad_enum']); // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

            <!--        -->
            <div class="row">
                <fieldset>
                    <legend>Dodanie</legend>
                    <div class="col-lg-6">
                        Zákazník:
                        <?php echo $this->ciselniky['zakazniciModel']->getNazov($this->vydaj['zakaznik_enum']); // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
                        Prepravca:
                        <?php echo $this->ciselniky['prepravciModel']->getNazov($this->vydaj['prepravca_enum']); // render the user name field here ?>
                    </div>
            </div>
            <!--        -->
            <div class="row">
                <div class="col-lg-6">
                    ŠPZ:
                    <?php echo $this->vydaj['prepravca_spz']; // render the user name field here ?>
                </div>
                </fieldset>
            </div>
            <!---->

            <div class="row">
                <fieldset>
                    <legend>Množstvo</legend>
                    <div class="col-lg-6">
                            Váha:
                        <?php echo number_format($this->vydaj['q_tony_merane'], 2, ",", " ").' t'; // render the user name field here ?>
                    </div>


                    <div class="col-lg-6">
                        Objem:
                        <?php echo number_format($this->vydaj['q_m3_merane'], 2, ",", " ").' m<sup>3</sup>'; // render the user name field here ?>
                    </div>

            </div>
            <div class="row">


                <div class="col-lg-6">
                    Priestor:
                    <?php echo number_format($this->vydaj['q_prm_merane'], 2, ",", " ").' PRM'; // render the user name field here ?>
                </div>
                <div class="col-lg-6">
                    Vlhkosť:
                    <?php echo number_format($this->vydaj['q_vlhkost'], 2, ",", " ").' %'; // render the user name field here ?>
                </div>
                </fieldset>
            </div>


            <div class="row">
                <fieldset>
                    <legend>Materiál</legend>
                    <div class="col-lg-6">
                        Typ:
                        <?php echo $this->ciselniky['materialyTypyModel']->getNazov($this->vydaj['material_typ_enum']); // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
                        Druh:
                        <?php echo $this->ciselniky['materialyDruhyModel']->getNazov($this->vydaj['material_druh_enum']); // render the user name field here ?>
                    </div>

            </div>

            <div class="row">
                    <div class="col-lg-12">
                        Stroj:
                        <?php echo $this->ciselniky['strojeModel']->getNazov($this->vydaj['stroj_enum']); // render the user name field here ?>
                    </div>
            </div>

            <div class="row">
                <fieldset>
                    <legend>Doplňujúce informácie</legend>
                    <div class="col-lg-6">
                        Stav:
                        <?php echo $this->ciselniky['transakcieStavyModel']->getNazov($this->vydaj['stav_transakcie']); // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
                        Chyba:
                        <?php if ($this->vydaj['chyba'] == 1 ) echo 'áno';
                        else echo 'nie'; // render the user name field here ?>
                    </div>
            </div>
            <br>
            <div class="row">

                <div class="col-lg-12">
                    Poznámka:
                    <?php if ($this->vydaj['poznamka'] == '' || $this->vydaj['poznamka'] == '0' ) echo 'žiadna poznámka';
                    else echo $this->vydaj['poznamka']; // render the user name field here ?>
                </div>
                </fieldset>
            </div>



            <br>

            <div class="row">


                <div class="col-lg-6 tright">
                    <?php if ($this->vydaj['chyba'] == 0 ){?>

                        <a href="#" class="btn-danger btn" data-toggle="modal" data-target="#myModal">Chyba</a>

                        <!--                        <a href="--><?php
//                            echo $this->url(array('controller'=>'vydaje', 'action'=>'mark-as-error', 'module'=>'skladnik', 'id'=>$this->vydaj['ts_vydaje_id'], 'fromAction' => $this->fromAction));?><!--" class="btn-danger btn" >-->
<!--                        Chyba-->
<!--                        </a>-->
                    <?php } ?>

                    <?php

                    $merna_jednotka = $this->ciselniky['zakazniciModel']->getMernaJednotka($this->vydaj['zakaznik_enum']);

                    if ($merna_jednotka == 1 )
                        echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Vydaje", "action"=>"printton", "id"=>$this->vydaj['ts_vydaje_id'], "fromAction" => "list",
                            )).'" target="_blank">Tlačiť</a>'
                    //                <!--                    printton-->
                    ?>

                    <?php  if ($merna_jednotka == 2 )
                        echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Vydaje", "action"=>"printprm", "id"=>$this->vydaj['ts_vydaje_id'], "fromAction" => "list",
                            )).'" target="_blank">Tlačiť</a>'
                    //                <!--                   printprm-->
                    ?>
                    <?php  if ($merna_jednotka == 3 )
                        echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Vydaje", "action"=>"printm3", "id"=>$this->vydaj['ts_vydaje_id'], "fromAction" => "list",
                            )).'" target="_blank">Tlačiť</a>'
                    //                <!--                    printm3-->
                    //                                ?>


                </div>

                <div class="col-lg-6">
                    <!--            <dt>&nbsp;</dt>-->
                    <a href="<?php echo $this->url(array(
                        'controller' => 'vydaje',
                        'action' => $this->fromAction,
                        'module' => 'skladnik'
                    ), null, true) ?>"  type="button" class="btn btn-warning form-control">Späť</a>
                </div>

            </div>

        </div>
    </div>


    <div id="myModal" class="modal fade" role="dialog">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Označiť výdaj ako chybný?</h4>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Nie</button>
                    <a href="<?php echo $this->url(array('controller'=>'vydaje', 'action'=>'mark-as-error', 'module'=>'skladnik', 'id'=>$this->vydaj['ts_vydaje_id'], 'fromAction' => $this->fromAction));?>" class="btn btn-primary" >Áno</a>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->

    </div>
