<?php
$this->headTitle($this->title);

?>


<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>


<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>stroj</th>
        <th>počet spracovaných transakcií</th>
    </tr>

    <?php foreach($this->strojeModel->getIds() as $strojId) : ?>
        <tr>
            <td><?php echo $this->strojeModel->getNazov($strojId);?></td>
            <td><?php echo $this->strojeModel->getCountTransactionsByStrojId($strojId);?></td>
        </tr>
    <?php endforeach; ?>
</table>


<div class="row">
    <div class="col-lg-12">
        <div id="pie-chart"></div>
    </div>
</div>


<script>

    Morris.Donut({
        element: 'pie-chart',
        data: [ <?php $counter = 0;
    foreach($this->strojeModel->getIds() as $strojId) : ?>
            { label: <?php echo '"'.$this->strojeModel->getNazov($strojId).'"';?>, value: <?php echo $this->strojeModel->getCountTransactionsByStrojId($strojId); ?> } <?php $counter++; if ($counter < count($this->strojeModel->getIds()) ) echo ','; ?>
            <?php endforeach; ?>
        ]

    });

</script>




