<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
?>

<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>

<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#fancy_table').DataTable( {
            "order": [[ 1, "desc" ]],
            columnDefs: [
                { "sType": "title-string", "aTargets": [ 1 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
            ],
            initComplete: function () {
                var api = this.api();
                var abc = 0;
                api.columns().indexes().flatten().each( function ( i ) {
                    var column = api.column( i );
                    if (i != abc) {
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    }
                } );
            }
        } );
    } );
</script>
<!--
<div class="row table-responsive">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Prehľad vyťaženia strojov</h3>
            </div>
            <div class="panel-body overflow">
                <div id="morris-bar-chart"></div>
                <div class="text-right">
                    <a href="#tabulka">Prejsť na tabuľku <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
-->

<!--Taby-->
<ul class="nav nav-tabs">
    <?php
    foreach($this->rokyModel->getIds() as $rokId):?>
    <li <?php if ($rokId == 1){echo "class=\"active\"";}?>><a data-toggle="tab" href="#menu<?php echo $rokId;?>"><?php echo $this->rokyModel->getNazov($rokId);?></a></li>
    <?php endforeach; ?>
</ul>

<div class="tab-content">
    <?php
    foreach($this->rokyModel->getIds() as $rokId):?>
        <div id="<?php echo "menu".$rokId;?>" <?php if ($rokId == 1){echo "class=\"tab-pane fade in active\"";} else { echo "class=\"tab-pane fade\"";}?>>
            <div id="" class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                <tr>
                    <!--
                    <th>ID</th>
                    -->
                    <th>Stroj</th>
                    <th>Spracovanie tony</th>
                    <th>Spracovanie PRM</th>
                    <th>Spracovanie m<sup>3</sup></th>
                </tr>


                <?php foreach($this->strojeModel->getIds() as $strojId) :
                    $sums = $this->strojeModel->getQuantitiesByYearIdStrojId($rokId,$strojId);
                    ?>
                    <tr>
                        <td><?php echo $this->escape($this->strojeModel->getNazov($strojId));?></td>

                        <td><?php echo number_format($sums['q_tony_merane'], 2, ",", " ");?></td>

                        <td><?php echo number_format($sums['q_prm_merane'], 2, ",", " ");?></td>

                        <td><?php echo number_format($sums['q_m3_merane'], 2, ",", " ");?></td>
                    </tr>
                <?php endforeach; ?>
                </table>
            </div>

        </div>
    <?php endforeach; ?>

</div>

<br>

<script>


    Morris.Bar({
        element: 'morris-bar-chart',
        data: [
            <?php $counter = 0;
               foreach($this->strojeModel->getIds() as $strojId) : ?>
            { label: <?php echo "'".$this->strojeModel->getNazov($strojId)."',";?>
                value: <?php echo $this->strojeModel->getCountTransactionsByStrojId($strojId); ?> }

            <?php $counter++; if ($counter < count($this->strojeModel->getIds()) ) echo ','; ?>
            <?php endforeach; ?>

    ],
    xkey: 'label',
        ykeys: ['value'],
        labels: ['Počet spracovaných transakcií'],
        barRatio: 15,
        xLabelAngle: 35,
        hideHover: 'auto',
        resize: false
    });


//    Morris.Donut({
//        element: 'pie-chart',
//        data: [ <?php //$counter = 0;
//    foreach($this->strojeModel->getIds() as $strojId) : ?>
//            { label: <?php //echo '"'.$this->strojeModel->getNazov($strojId).'"';?>//, value: <?php //echo $this->strojeModel->getCountTransactionsByStrojId($strojId); ?>// } <?php //$counter++; if ($counter < count($this->strojeModel->getIds()) ) echo ','; ?>
<!--            --><?php //endforeach; ?>
//        ]
//
//    });

</script>




