<?php
$this->headTitle($this->title); ?>

<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>


<div class="row">

    <div id="morris-area-chart"></div>

</div>

<div class="row">


    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Stroj</th>
            <th>Vyťaženie</th>

        </tr>


       <?php foreach ($this->vytazenieStrojov as $key => $val) :

          ?>
            <tr>
                <td><?php  echo $key ?> //todo get nazov</td>
                <td><?php echo $val.'%';?></td>


            </tr>


        <?php endforeach; ?>


</div>







<script>
    // Area Chart
    Morris.Bar({
        element: 'morris-area-chart',

        data: <?php echo json_encode($this->vytazenieStrojov);?>,

//        xkey: '1',
//        ykeys: ['0'],
        labels: ['Stav (t)'],
        pointSize: 2,
        hideHover: 'auto',
        smooth: true,
        resize: true,
        barColors: ['#000']


    });



</script>



<?php //echo json_encode($this->vytazenieStrojov);?>
