<?php
$this->headTitle($this->title);
?>


<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Stroj</th>
        <th>typ</th>
        <th>úpravy</th>
    </tr>


    <?php foreach($this->stroje as $stroj) : ?>
        <tr>
            <td><?php echo $this->escape($stroj->stroje_id);?></td>
            <td><?php echo $this->escape($stroj->nazov_stroja);?></td>
            <td><?php echo $this->escape($this->strojeTypy->getNazov($stroj->typ_stroja));?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Stroje',
                    'action'=>'edit', 'id'=>$stroj->stroje_id));?>">Upraviť</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>