<h1 >Externá dodávka - detail</h1>
<!--<hr>-->
<div class="col-lg-5">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-th-large"></i> Detail ext. dodávky  <?php echo  $this->dodavka['doklad_cislo'];?></h3>
        </div>
        <div class="panel-body">

            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-calendar"></i> Dátum externej dodávky</legend>

                    <div class="col-lg-6">
                        Dátum:
                        <?php echo  date("d.m.Y", strtotime($this->dodavka['datum_xdodavky_d'])); // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-user"></i> Zákazník</legend>
                    <div class="col-lg-6">
                        Zákazník:
                        <?php echo $this->ciselniky['zakazniciModel']->getNazov( $this->dodavka['zakaznik_enum']); // render the user name field here ?>
                    </div>
            </div>


            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-truck"></i> Dodanie</legend>
                    <div class="col-lg-6">
                        Dodávateľ:
                        <?php echo $this->ciselniky['dodavateliaModel']->getNazov( $this->dodavka['dodavatel_enum']); // render the user name field here ?>
                    </div>


            </div>

            <div class="row">
                <div class="col-lg-6">
                        Prepravca:
                        <?php echo $this->ciselniky['prepravciModel']->getNazov( $this->dodavka['prepravca_enum']); // render the user name field here ?>
                    </div>
                <div class="col-lg-6">
                    ŠPZ:
                    <?php echo  $this->dodavka['prepravca_spz']; // render the user name field here ?>
                </div>
                </fieldset>
            </div>

            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-cubes"></i> Množstvo</legend>
                    <div class="col-lg-6">
                        Váha:
                        <?php echo number_format( $this->dodavka['q_tony_merane'], 2, ",", " ").' t'; // render the user name field here ?>
                    </div>


                    <div class="col-lg-6">
                        Objem:
                        <?php echo number_format( $this->dodavka['q_m3_merane'], 2, ",", " ").' m<sup>3</sup>'; // render the user name field here ?>
                    </div>

            </div>
            <div class="row">


                <div class="col-lg-6">
                    Priestor:
                    <?php echo number_format( $this->dodavka['q_prm_merane'], 2, ",", " ").' PRM'; // render the user name field here ?>
                </div>
                <div class="col-lg-6">
                    Vlhkosť:
                    <?php echo number_format( $this->dodavka['q_vlhkost'], 2, ",", " ").' %'; // render the user name field here ?>
                </div>
                </fieldset>
            </div>


            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-tree"></i> Materiál</legend>
                    <div class="col-lg-6">
                        Typ:
                        <?php echo $this->ciselniky['materialyTypyModel']->getNazov( $this->dodavka['material_typ_enum']); // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
                        Druh:
                        <?php echo $this->ciselniky['materialyDruhyModel']->getNazov( $this->dodavka['material_druh_enum']); // render the user name field here ?>
                    </div>

            </div>


            <div class="row">
                <fieldset>
                    <legend><i class="fa fa-info-circle"></i> Doplňujúce informácie</legend>
                    <div class="col-lg-6">
                        Stav:
                        <?php echo $this->ciselniky['transakcieStavyModel']->getNazov( $this->dodavka['stav_transakcie']); // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
                        Chyba:
                        <?php if ( $this->dodavka['chyba'] == 1 ) echo 'áno';
                        else echo 'nie'; // render the user name field here ?>
                    </div>
            </div>
            <br>
            <div class="row">

                <div class="col-lg-12">
                    Poznámka:
                    <?php if ( $this->dodavka['poznamka'] == '' ||  $this->dodavka['poznamka'] == '0' ) echo 'žiadna poznámka';
                    else echo  $this->dodavka['poznamka']; // render the user name field here ?>
                </div>
                </fieldset>
            </div>



            <br>

            <div class="row">


                <div class="col-lg-6 tright">




                </div>

                <div class="col-lg-6">
                    <!--            <dt>&nbsp;</dt>-->
                    <a href="<?php echo $this->url(array(
                        'controller' => $this->fromController,
                        'action' => $this->fromAction,
                        'id' => $this->fromId
                    ), null, true) ?>"  type="button" class="btn btn-warning form-control">Späť</a>
                </div>

            </div>

        </div>
    </div>