<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
?>


<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#fancy_table').DataTable( {
            "order": [[ 1, "desc" ]],
            columnDefs: [
                { "sType": "title-string", "aTargets": [ 8 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
            ],
            initComplete: function () {
                var api = this.api();
                var abc = 0;
                api.columns().indexes().flatten().each( function ( i ) {
                    var column = api.column( i );
                    if (i != abc) {
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    }
                } );
            }
        } );
    } );
</script>
<!--
<div class="alert alert-dismissable alert-info">
<!--    <a href="--><?php //echo $this->url(array('controller'=>'ExternaDodavka',
//    'action'=>'add', 'fromAction' => 'list'));?><!--">-->
<!--        --><?php //echo '<img src="'.$this->baseUrl().'/images/pridat.png" alt="pridat">'; ?>
<!--        Pridať nový výdaj</a>-->
<!--    <a href="--><?php //echo '../' ?><!--" type="button" class="btn btn-warning right">Späť</a>-->
<!--</div>-->



<?php
$notifikacie     = new Application_Model_Notifikacie();
$notif_info = $notifikacie->getStatusArray();
$count_notif = $notif_info['total'];
$externe_dodavky_w = $notif_info['externe_dodavky_waitings'];
$externe_dodavky_e = $notif_info['externe_dodavky_errors'];
?>


<p>
    <a href="<?php echo $this->url(array('controller'=>'externaDodavka',
        'action'=>'add', 'fromAction' => 'list', "fromController" => 'externaDodavka'));?>" type="button" class="btn btn-success">
        Pridať dodávku
    </a>

    <a href="<?php echo $this->url(array('controller'=>'ExternaDodavka',
        'action'=>'list'));?>" type="button" class="btn btn-info">
        Všetky dodávky
    </a>

    <?php if ($externe_dodavky_w >0) { ?>
        <a href="<?php echo $this->url(array(
            'controller' => 'externaDodavka',
            'action' => 'waitings'
        ), null, true) ?>" type="button" class="btn btn-warning">Na schválenie (<?php echo $externe_dodavky_w; ?>) </a>
    <?php }
    if ($externe_dodavky_e > 0) {
        ?>
        <a href="<?php echo $this->url(array(
            'controller' => 'externaDodavka',
            'action' => 'errors'
        ), null, true) ?>" type="button" class="btn btn-danger"> Chybné (<?php echo $externe_dodavky_e   ; ?>) </a>
    <?php } ?>
</p>


<div class="table-responsive">
    <table id="fancy_table" class="table table-hover table-striped" >

        <thead>
        <tr class="tableizer-firstrow">
            <!--        <th>ID</th>-->
            <th>Detail</th>
            <th>Dátum</th>
            <!--              <th>doklad číslo</th>-->
            <th>Zákazník</th>
            <th>Prepravca</th>
            <!--              <th> SPZ</th>-->
            <th>Tony</th>
            <!--        <th>tony v</th>-->
                    <th>m<sup>3</sup></th>
            <!--        <th>m3 v</th>-->
                    <th>PRM</th>
            <!--        <th>prm v</th>-->
            <th>Vlhkosť</th>
            <th>Doklad</th>
            <th>Materiál</th>
            <!--              <th>material druh</th>-->
            <th class="col-stav">Stav</th>
            <!--              <th >chyba</th>-->
            <th class="col-upravy">Úpravy</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <!--        <th>ID</th>-->
            <th></th>
            <th>Dátum výdaju</th>
            <!--        <th>doklad číslo</th>-->
            <th>zákazník</th>
            <th></th>
            <!--        <th> SPZ</th>-->
            <th>tony m</th>
            <th>vlhkost</th>
            <!--        <th>tony v</th>-->
                    <th>m3 m</th>
            <!--        <th>m3 v</th>-->
                    <th>prm m</th>
            <!--        <th>prm v</th>-->

            <th>assss</th>
            <th>material typ</th>
<!--                    <th>úpravy</th>-->
        </tr>
        </tfoot>

        <tbody>

        <?php foreach($this->externeDodavky as $externa_dodavka) : ?>
            <?php if ($externa_dodavka->chyba == 1 ) echo "<tr class='danger'> ";
            else echo   "<tr>";
            ?>
<!--            <td>--><?php //echo $this->escape($vydaj->ts_vydaje_id);?><!--</td>-->
            <td class="center"> <a href="<?php echo $this->url(array('controller'=>'externaDodavka',
                    'action'=>'preview', 'id'=>$externa_dodavka->doklad_cislo, 'fromAction' => 'list'));?>">
                    <i class="fa fa-eye"></i>
                </a></td>
            <td>
            <?php
            $date = date('Y/M/d', strtotime($this->escape($externa_dodavka->datum_xdodavky_d)));
            echo $date ;?>
            </td>
<!--               <td>--><?php //echo $this->escape($vydaj->doklad_cislo);?><!--</td>-->
            <td><?php echo $this->escape($this->zakaznici->getNazov($externa_dodavka->zakaznik_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($externa_dodavka->prepravca_enum));?></td>
<!--            <td>--><?php //echo $this->escape($vydaj->prepravca_spz);?><!--</td>-->
            <td><?php echo number_format($this->escape($externa_dodavka->q_tony_merane), 2, ",", " ");?></td>


<!--            <td>--><?php //echo $this->escape($vydaj->q_tony_vypocet);?><!--</td>-->
            <td><?php echo number_format($this->escape($externa_dodavka->q_m3_merane), 2, ",", " ");?></td>
<!--            <td>--><?php //echo $this->escape($vydaj->q_m3_vypocet);?><!--</td>-->
            <td><?php echo number_format($this->escape($externa_dodavka->q_prm_merane), 2, ",", " ");?></td>
<!--            <td>--><?php //echo $this->escape($vydaj->q_prm_vypocet);?><!--</td>-->
<td>
                <?php
            if ($externa_dodavka->q_vlhkost == 0.00){
                echo "-";
            }else {
                echo number_format($this->escape($externa_dodavka->q_vlhkost), 2, ",", " ") . "%";
            }
            ?>
            </td>
            <td><?php echo $this->escape($externa_dodavka->doklad_cislo);?></td>
            <td><?php echo $this->escape($this->materialyTypy->getNazov($externa_dodavka->material_typ_enum));?></td>
<!--            <td>--><?php //echo $this->escape($this->materialyDruhy->getNazov($vydaj->material_druh_enum));?><!--</td>-->
            <td class="center">

<!--            --><?php //echo $this->escape($this->transakcieStavy->getNazov($vydaj->stav_transakcie));?>
            <?php
            if  ( $externa_dodavka->stav_transakcie == 2 ) {
//                    echo '<img src="'.$this->baseUrl().'/images/schvalene.png" alt="schvalene">';
                echo '<i class="fa fa-check-circle-o"></i>';
            }
            else if ($externa_dodavka->stav_transakcie == 1 ) {
//                    echo '<img src="'.$this->baseUrl().'/images/caka.png" alt="caka na schvalenie">';
                echo '<i class="fa fa-clock-o"></i>';
            }
            else {
//                    echo '<img src="'.$this->baseUrl().'/images/zrusene.png" alt="zrusene">';
                echo '<i class="fa fa-times-circle-o"></i>';
            }
            ?>


            </td>
<!--            <td>-->
<!--                --><?php
//                if ($this->escape($vydaj->chyba) == 1)
//                {echo "áno";}
//                else {echo "nie";}
//                ?><!--</td>-->
            <td>
                <a href="<?php echo $this->url(array('controller'=>'ExternaDodavka',
                'action'=>'delete', 'tx_dodavka_id'=>$externa_dodavka->tx_dodavka_id, 'fromAction' => 'list'));?>"><i class="fa fa-trash-o"></i></a>

                <a href="<?php echo $this->url(array('controller'=>'ExternaDodavka',
                'action'=>'edit', 'tx_dodavka_id'=>$externa_dodavka->tx_dodavka_id,  'fromAction' => 'list'));?>"><i class="fa fa-pencil-square-o"></i></a>

                <?php

//                echo '<a href="'.$this->url(array("controller"=>"ExternaDodavka", "action"=>"print", "id"=>$externa_dodavka->tx_dodavka_id, "fromAction" => "list",
//                    )).'" target="_blank"><i class="fa fa-print"></i></a>'

//            $merna_jednotka = $this->zakaznici->getMernaJednotka($externa_dodavka->zakaznik_enum);
            ?>


            <?php  if ($merna_jednotka == 1 )
//                echo '<a href="'.$this->url(array("controller"=>"ExternaDodavka", "action"=>"printton", "id"=>$externa_dodavka->tx_dodavka_id, "fromAction" => "list",
//                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
            //<!--                    printton-->
            ?>

            <?php  if ($merna_jednotka == 2 )
//                echo '<a href="'.$this->url(array("controller"=>"ExternaDodavka", "action"=>"printprm", "id"=>$externa_dodavka->tx_dodavka_id, "fromAction" => "list",
//                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
            //<!--                   printprm-->
            ?>
            <?php  if ($merna_jednotka == 3 )
//                echo '<a href="'.$this->url(array("controller"=>"Externadodavka", "action"=>"printm3", "id"=>$externa_dodavka->tx_dodavka_id, "fromAction" => "list",
//                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
            //<!--                    printm3-->
            ?>

            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
</div>