<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/fancy_table_ext.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/table_features.js'); //tuto su prepocty priemer a sum


$notifikacie     = new Application_Model_Notifikacie();
$notif_info = $notifikacie->getStatusArray();
$count_notif = $notif_info['total'];
$externe_dodavky_w = $notif_info['externe_dodavky_waitings'];
$externe_dodavky_e = $notif_info['externe_dodavky_errors'];


$controller = 'externaDodavka';
$this->prijmybuttons($this,$externe_dodavky_w,$externe_dodavky_e,$controller);
?>

<div class="table-responsive">
    <table id="fancy_table" class="table table-hover table-striped" >

        <thead>
        <tr class="tableizer-firstrow">

            <th class="no-print">Detail</th>
            <th>Dátum</th>
            <th>Zákazník</th>
            <th>Dodávateľ</th>
            <th>Prepravca</th>
            <th>Tony</th>
            <th>m<sup>3</sup></th>
            <th>PRM</th>
            <th>Vlhkosť</th>
            <th>Doklad</th>
            <th>Materiál</th>
            <th class="col-stav">Stav</th>
            <th class="col-upravy no-print">Úpravy</th>
        </tr>
        </thead>

        <tfoot>
        <tr>

            <th></th>
            <th>Dátum výdaju</th>
            <th>zákazník</th>
            <th>dodávateľ</th>
            <th></th>
            <th>tony m</th>
            <th>vlhkost</th>
            <th>m3 m</th>
            <th>prm m</th>
            <th>assss</th>
            <th>material typ</th>

        </tr>
        </tfoot>

        <tbody>

        <?php foreach($this->externeDodavky as $externa_dodavka) : ?>
            <?php if ($externa_dodavka->chyba == 1 ) echo "<tr class='danger'> ";
            else echo   "<tr>";
            ?>
            <td class="center no-print"> <a href="<?php echo $this->url(array('controller'=>'externaDodavka',
                'action'=>'preview', 'id'=>$externa_dodavka->doklad_cislo, 'fromAction' => 'waitings'));?>">
                     <i class="fa fa-eye"></i>
                </a></td>
            <td>
            <?php
            $date = date('Y/M/d', strtotime($this->escape($externa_dodavka->datum_xdodavky_d)));
            echo $date ;?>
            </td>
            <td><?php echo $this->escape($this->zakaznici->getNazov($externa_dodavka->zakaznik_enum));?></td>
            <td><?php echo $this->escape($this->dodavatelia->getNazov($externa_dodavka->dodavatel_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($externa_dodavka->prepravca_enum));?></td>
            <td class="tonaz"><?php echo number_format($this->escape($externa_dodavka->q_tony_merane), 2, ",", " ");?></td>
            <td><?php echo number_format($this->escape($externa_dodavka->q_m3_merane), 2, ",", " ");?></td>
            <td><?php echo number_format($this->escape($externa_dodavka->q_prm_merane), 2, ",", " ");?></td>
            <td class="vlhkost">
                <?php
                    if ($externa_dodavka->q_vlhkost == 0.00){
                        echo "-";
                    }else {
                        echo number_format($this->escape($externa_dodavka->q_vlhkost), 2, ",", " ") . "%";
                    }
            ?>
            </td>
            <td><?php echo $this->escape($externa_dodavka->doklad_cislo);?></td>
            <td><?php echo $this->escape($this->materialyTypy->getNazov($externa_dodavka->material_typ_enum));?></td>
             <td class="center">
                <?php
            $this->stavy($externa_dodavka);
            ?>
            </td>
            <td>
                <?php

            $merna_jednotka = '666';
            $this->tlacbuttons($this,$merna_jednotka,$externa_dodavka->tx_dodavka_id,$controller);
            ?>

            </td>
        </tr>
    <?php endforeach; ?>
        </tbody>
    </table>

    <div id="tonaz">   </div>
    <div id="priemer"> </div>

</div>