<?php
$this->title = "Pridanie Dodávateľa";
$this->headTitle($this->title);

//echo $this->form ;
//?>

<div class="col-lg-5">
     <div class="panel panel-green">
         <div class="panel-heading">
             <h3 class="panel-title">Detail transakcie </h3>
         </div>
         <div class="panel-body">
             <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                   method="<?php echo $this->escape($this->form->getMethod()) ?>"
                   enctype="multipart/form-data" class="normal">

                 <?php echo $this->form->id; ?>

                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-6">
                             <!--                        Dátum:-->
                             <?php echo $this->form->interny_kod; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->

                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-6">
                             <!--                        Dátum:-->
                             <?php echo $this->form->meno; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->

                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-6">
                             <!--                        Dátum:-->
                             <?php echo $this->form->nazov_spolocnosti; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->


                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-6">
                             <!--                        Dátum:-->
                             <?php echo $this->form->ico; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->

                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-6">
                             <!--                        Dátum:-->
                             <?php echo $this->form->ic_dph; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->

                 <div class="row">
                     <fieldset>
                         <!--                    <legend>Dátum príjmu</legend>-->

                         <div class="col-lg-12">
                             <!--                        Dátum:-->
                             <?php echo $this->form->adresa; // render the user name field here ?>
                         </div>
                     </fieldset>
                 </div>
                 <!---->

                 <div class="row">

                     <div class="col-lg-6">

                         <?php echo $this->form->potvrdzujuceTlacidlo; // render the user name field here ?>

                     </div>


                     <div class="col-lg-6">
                         <dt>&nbsp;</dt>
                         <a href="<?php
                         //    pageManager
                         echo $this->url(array(
                             'controller' => 'dodavatelia',
                             'action' => 'list'
                         ), null, true) ?>"  type="button" class="btn btn-warning">Späť</a>
                     </div>
                 </div>

                 </form>
 </div>
         </div>
     </div>