<?php
$this->headTitle($this->title);

?>
<p>
<a href="<?php echo $this->url(array('controller'=>'Dodavatelia',
    'action'=>'add', 'fromAction' => 'list'));?>" type="button" class="btn btn-success">Pridať dodávateľa</a>
</p>


    <!---->
<!--<div class="alert alert-dismissable alert-warning">-->
<!--    kontrolny vypis</br>-->
<!---->
<!--</div>-->



<div id=".col-lg-12" class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>ID</th>
            <th>Meno</th>
            <th>Názov spoločnosti</th>
            <th>IČO</th>
            <th>Upraviť</th>
        </tr>

        <?php foreach($this->dodavatelia as $dodavatel) : ?>
            <tr>

                <td> <?php echo $this->escape($dodavatel->dodavatelia_id); ?></td>
                <td> <?php echo $this->escape($dodavatel->meno ); ?></td>
                <td> <?php echo $this->escape($dodavatel->nazov_spolocnosti ); ?></td>
                <td> <?php echo $this->escape($dodavatel->ico ); ?></td>
                <td>  <a href="<?php echo $this->url(array('controller'=>'Dodavatelia',
                        'action'=>'edit', 'dodavatelia_id'=>$dodavatel->dodavatelia_id));?>">Upraviť</a></td>
            </tr>
        <?php endforeach; ?>

    </table>

<!--    <a href="--><?php
//    pageManager
//    echo $this->url(array(
//        'controller' => 'dodavatelia',
//        'action' => $this->fromAction
//    ), null, true) ?><!--"  type="button" class="btn btn-warning">Späť</a>-->

</div>