<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('wh50k');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <!--  *********** HEAD JS + JQUERY INCLUDES   ******** -->

    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jjquery.js';?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/bootstrap.min.js';?>"></script>

    <!--jquery kamos so zendom-->
    <?php
    echo $this->jQuery()
//    ->setVersion('1.5.1')    // toto nacita najnovsie ENG z netu
//    ->setUiVersion('1.8.11') // toto je k tomu a tiez je to ENG
        ->enable()
        ->uiEnable(); ?>
    <!--jquery-->

    <!-- ostatne JS + jquery pre fancy tables    -->
    <?php

    //    $this->inlineScript()->appendFile($this->baseUrl().'/js/raphael.min.js');
    //    $this->inlineScript()->appendFile($this->baseUrl().'/js/morris.min.js');
    //    $this->inlineScript()->appendFile($this->baseUrl().'/js/morris-data.js');
    //    $this->inlineScript()->appendFile($this->baseUrl().'/js/shCore.js');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jquery.dataTables.min.js');
    echo $this->inlineScript(); ?>

    <!--  *********** KONIEC HEAD JS + JQUERY INCLUDES   ******** -->

    <!--   ************ HEAD CSS INCLUDES *****************   -->

    <?php  $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/sb-admin.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/bootstrap.min.css'); ?>
    <?php  $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/morris.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/font-awesome.min.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/jquery.dataTables.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/js/jquery/jquery-ui-dark.css'); ?>


    <?php echo $this->headLink(); ?>


<body>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->loginTitle; ?></h3>
                </div>
                <div class="panel-body">
                    <?php
                    if ( $this->wrongCredentials == true ){
                        ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="alert alert-danger">
                                    Zadali ste <strong>nesprávne</strong> prihlasovacie údaje.
                                </div>
                            </div>
                        </div>
                    <?php
                    }
                    else{
                        //tento kod by siel ked je nie je chybne zadane login a heslo
                    }
                    ?>


                    <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                          method="<?php echo $this->escape($this->form->getMethod()) ?>"
                          enctype="multipart/form-data" role="form">

                        <fieldset>
                            <div class="form-group">
                                <!--                                    <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>-->
                                <?php echo $this->form->email ?>

                            </div>
                            <div class="form-group">
                                <!--                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">-->
                                <?php echo $this->form->password; ?>
                            </div>

                            <!-- Change this to a button or input when using this as a form -->
                            <!--                                <a href="index.html" class="btn btn-lg btn-success btn-block">Prihlásiť</a>-->
                            <?php echo $this->form->submitButton; ?>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- jQuery -->
<script src="../bower_components/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="../dist/js/sb-admin-2.js"></script>

</body>
