<?php
$this->headTitle($this->title);
?>

<!--toto mozeme casom vymazat len kontrolny vypis
<?php echo($this->podsklady->getNazov(1));?>
<?php echo($this->prepravci->getNazov(1));?>
<?php echo($this->zakaznici->getNazov(1));?>
-->


<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Dátum výdaju</th>
        <th>sklad</th>
        <th>podsklad</th>
        <th>zákazník</th>
        <th>prepravca</th>
        <th>prepravca SPZ</th>
        <th>tony</th>
        <th>doklad číslo</th>
        <th>chyba</th>
        <th>úpravy</th>
    </tr>

    <?php $suma = 0; $pocet = 0;?>

    <?php foreach($this->vydaje as $vydaj) : ?>
        <tr>
            <td><?php echo $this->escape($vydaj->ts_vydaje_id);?></td>
            <td><?php echo $this->escape($vydaj->datum_vydaju_d);?></td>
            <td><?php echo $this->escape($this->sklady->getNazov($vydaj->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($vydaj->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->zakaznici->getNazov($vydaj->zakaznik_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($vydaj->prepravca_enum));?></td>
            <td><?php echo $this->escape($vydaj->prepravca_spz);?></td>
            <td><?php echo $this->escape($vydaj->q_tony_merane);?></td>
            <td><?php echo $this->escape($vydaj->doklad_cislo);?></td>
            <td>
                <?php
                if ($this->escape($vydaj->chyba) == 0)
                {echo "chyba";}
                else {echo "OK";}
                ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'vydaje',
                    'action'=>'delete', 'ts_vydaje_id'=>$vydaj->ts_vydaje_id));?>">Zmazať</a>
                <a href="<?php echo $this->url(array('controller'=>'vydaje',
                    'action'=>'edit', 'ts_vydaje_id'=>$vydaj->ts_vydaje_id));?>">Upraviť</a>
            </td>


            <?php $this->suma += $this->escape($vydaj->q_tony_merane); $this->pocet += 1;?>
        </tr>
    <?php endforeach; ?>

    <?php

    $priemer = $this->suma/$this->pocet;



    ;?>





    <tr>
        <td>Priemer</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><?php echo $priemer;?></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>

<a href="<?php echo $this->url(array('controller'=>'vydaje',
    'action'=>'add')); ?>">Pridať</a>