<?php
$this->headTitle($this->title);

$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
?>


<script type="text/javascript" language="javascript" class="init">


    $(document).ready(function() {
        $('#fancy_table').DataTable( {

            "order": [[ 1, "desc" ]],
            columnDefs: [
                { "sType": "title-string", "aTargets": [ 8 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
            ],

            initComplete: function () {
                var api = this.api();
                var abc = 0;
                api.columns().indexes().flatten().each( function ( i ) {


                    var column = api.column( i );

                    if (i != abc) {

                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );

                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    }
                } );
            }
        } );

    } );


</script>
<!--
<div class="alert alert-dismissable alert-info">

    <a href="<?php echo $this->url(array('controller'=>'Vydaje',
        'action'=>'add'));?>">
        <?php echo '<img src="'.$this->baseUrl().'/images/pridat.png" alt="pridat">'; ?>
        Pridať nový výdaj</a>

    <a href="<?php echo '../' ?>" type="button" class="btn btn-warning right">Späť</a>
</div>
-->


<?php

$notifikacie     = new Application_Model_Notifikacie();


$notif_info = $notifikacie->getStatusArray();

$count_notif = $notif_info['total'];

$vydaje_w = $notif_info['vydaje_waitings'];
$vydaje_e = $notif_info['vydaje_errors'];

?>


<p>
    <a href="<?php echo $this->url(array('controller'=>'Vydaje',
        'action'=>'add'));?>" type="button" class="btn btn-success">
        Pridať výdaj
    </a>
<?php if ($vydaje_w >0) { ?>
    <a href="<?php echo $this->url(array(
        'controller' => 'vydaje',
        'action' => 'waitings'
    ), null, true) ?>" type="button" class="btn btn-warning">Na schválenie (<?php echo $vydaje_w; ?>) </a>
<?php }
    if ($vydaje_e > 0) {
        ?>
    <a href="<?php echo $this->url(array(
        'controller' => 'vydaje',
        'action' => 'errors'
    ), null, true) ?>" type="button" class="btn btn-danger"> Chybné (<?php echo $vydaje_e   ; ?>) </a>
    <?php } ?>
    </p>


<div class="table-responsive">
    <table id="fancy_table" class="table table-hover table-bordered table-striped" >

        <thead>
          <tr class="tableizer-firstrow">
              <!--        <th>ID</th>-->
                <th>Detail</th>
              <th>Dátum výdaju</th>
<!--              <th>doklad číslo</th>-->
              <th>sklad</th>
              <th class="col-podsklad">podsklad</th>
              <th>zákazník</th>
              <th>prepravca</th>
<!--              <th> SPZ</th>-->
              <th>tony m</th>
              <!--        <th>tony v</th>-->
              <!--        <th>m3 m</th>-->
              <!--        <th>m3 v</th>-->
              <!--        <th>prm m</th>-->
              <!--        <th>prm v</th>-->

              <th>material typ</th>
<!--              <th>material druh</th>-->
              <th class="col-stav">stav</th>
<!--              <th >chyba</th>-->
              <th class="col-upravy">úpravy</th>
          </tr>
        </thead>

    <tfoot>
    <tr>
<!--        <th>ID</th>-->
        <th></th>
        <th>Dátum výdaju</th>
<!--        <th>doklad číslo</th>-->
        <th>sklad</th>
        <th>podsklad</th>
        <th>zákazník</th>
        <th>prepravca</th>
<!--        <th> SPZ</th>-->
        <th>tony m</th>
<!--        <th>tony v</th>-->
<!--        <th>m3 m</th>-->
<!--        <th>m3 v</th>-->
<!--        <th>prm m</th>-->
<!--        <th>prm v</th>-->

        <th>material typ</th>
<!--        <th>material druh</th>-->
<!--        <th>stav </th>-->
<!--        <th>chyba</th>-->
<!--        <th>úpravy</th>-->
    </tr>
    </tfoot>

    <tbody>

    <?php foreach($this->vydaje as $vydaj) : ?>
        <?php if ($vydaj->chyba == 1 ) echo "<tr class='danger'> ";
        else echo   "<tr>";
        ?>
<!--            <td>--><?php //echo $this->escape($vydaj->ts_vydaje_id);?><!--</td>-->
            <td> <a href="<?php echo $this->url(array('controller'=>'Vydaje',
            'action'=>'preview', 'id'=>$vydaj->doklad_cislo));?>">
                     <?php echo '<img src="'.$this->baseUrl().'/images/zobrazit.png" alt="detail">'; ?>
                </a></td>
            <td>
            <?php
                $date = date('Y/M/d', strtotime($this->escape($vydaj->datum_vydaju_d)));
                echo $date ;?>
            </td>
<!--               <td>--><?php //echo $this->escape($vydaj->doklad_cislo);?><!--</td>-->
            <td><?php echo $this->escape($this->sklady->getNazov($vydaj->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($vydaj->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->zakaznici->getNazov($vydaj->zakaznik_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($vydaj->prepravca_enum));?></td>
<!--            <td>--><?php //echo $this->escape($vydaj->prepravca_spz);?><!--</td>-->
            <td><?php echo $this->escape($vydaj->q_tony_merane);?></td>
<!--            <td>--><?php //echo $this->escape($vydaj->q_tony_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($vydaj->q_m3_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($vydaj->q_m3_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($vydaj->q_prm_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($vydaj->q_prm_vypocet);?><!--</td>-->

            <td><?php echo $this->escape($this->materialyTypy->getNazov($vydaj->material_typ_enum));?></td>
<!--            <td>--><?php //echo $this->escape($this->materialyDruhy->getNazov($vydaj->material_druh_enum));?><!--</td>-->
            <td>

<!--            --><?php //echo $this->escape($this->transakcieStavy->getNazov($vydaj->stav_transakcie));?>
                <?php


                if  (strcmp('schvalene', $this->escape($this->transakcieStavy->getNazov($vydaj->stav_transakcie)) ) == 0 ) {

//                    echo '<img src="'.$this->baseUrl().'/images/schvalene.png" alt="schvalene">';
                    echo '<div class="schvalene"></div>';
                }
                else if (strcmp('caka na schvalenie', $this->escape($this->transakcieStavy->getNazov($vydaj->stav_transakcie)) ) == 0 ) {

//                    echo '<img src="'.$this->baseUrl().'/images/caka.png" alt="caka na schvalenie">';
                    echo '<div class="caka"></div>';
                }
                else {

//                    echo '<img src="'.$this->baseUrl().'/images/zrusene.png" alt="zrusene">';
                    echo '<div class="zrusene"></div>';
                }
                ?>


            </td>
<!--            <td>-->
<!--                --><?php
//                if ($this->escape($vydaj->chyba) == 1)
//                {echo "áno";}
//                else {echo "nie";}
//                ?><!--</td>-->
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Vydaje',
                    'action'=>'delete', 'ts_vydaje_id'=>$vydaj->ts_vydaje_id));?>">
                    <?php echo '<img src="'.$this->baseUrl().'/images/zmazat.png" alt="zmazat">'; ?>
                </a>

                <a href="<?php echo $this->url(array('controller'=>'Vydaje',
                    'action'=>'edit', 'ts_vydaje_id'=>$vydaj->ts_vydaje_id));?>">

                      <?php echo '<img src="'.$this->baseUrl().'/images/upravit.png" alt="upravit">'; ?>

            </a>
                <a href="<?php echo $this->url(array('controller'=>'Vydaje',
                    'action'=>'print', 'ts_vydaje_id'=>$vydaj->ts_vydaje_id, 'cislo_listku'=>$vydaj->doklad_cislo,
                    'spz'=>$vydaj->prepravca_spz));?>" target="_blank" >

                     <?php echo '<img src="'.$this->baseUrl().'/images/tlacit.png" alt="tlacit">'; ?>

                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>
