<?php //cast pre generaciu PDF

//povinne volanie loaderu
Zend_Loader::loadClass('Zend_Pdf');

function random_string($length) {
    $key = '';
    $keys = array_merge(range(0, 9), range('a', 'z'));

    for ($i = 0; $i < $length; $i++) {
        $key .= $keys[array_rand($keys)];
    }

    return $key;
}

try {
    //    1. bud vytvorim clear cisty ... 2.alebo otvaram existujuci layout
    //    $pdf = new Zend_Pdf();
    $filename = '../docs/pdf/vazny_listok_vydaj.pdf';

    //    nasleduje load
    $pdf = Zend_Pdf::load( $filename);

    // 1. vytvorim new page / 2. do premennej page, si dam prvu page v otvorenom pdf
    //   premenna $page je standard pre pdf loader a vie s nou robit velke veci
    //1. $page = new Zend_Pdf_Page(Zend_Pdf_Page::SIZE_A4);
    $page = $pdf->pages[0];

    // musis definovat font, tak nejaky drahy idealne z macu :D
//    $font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_HELVETICA);
    $font = Zend_Pdf_Font::fontWithPath('../public/fonts/arial.ttf');


    //get parametre na tlac z URL
    $id = $this->escape($this->vydaj['ts_vydaje_id']);
    $cislo_listku = $this->escape($this->vydaj['doklad_cislo']);
    $spz = $this->escape($this->vydaj['prepravca_spz']);

    $timestamp = $this->escape($this->vydaj['vznik_zaznamu_dtm']);
    $datum = date('d.m.Y', strtotime($timestamp));
    $cas = date('H:i:s', strtotime($timestamp));

    $druh =  $this->escape($this->materialyDruhy->getSkratka($this->vydaj['material_druh_enum']));
    $typ =  $this->escape($this->materialyTypy->getNazov($this->vydaj['material_typ_enum']));
    $sklad = $this->escape($this->sklady->getSkratka($this->vydaj['sklad_enum']));
    $podsklad = $this->escape($this->podsklady->getSkratka($this->vydaj['podsklad_enum']));

    $zakaznik = $this->zakaznici->getZakaznik($this->vydaj['zakaznik_enum']);
    $adresa = $zakaznik['adresa'];
    $ico = $zakaznik['ico'];
    $dph = $zakaznik['ic_dph'];
    $dodavatel = $zakaznik['nazov_spolocnosti'];
//    $dodavatel = $this->escape($this->zakaznici->getNazov($this->vydaj['zakaznik_enum']));

    $brutto = $this->vydaj['q_tony_merane_brutto'];
    $tara = $this->vydaj['q_tony_merane_tara'];
    $netto = $this->vydaj['q_tony_merane'];

    //  do tej page, ktoru som si vyssie vybral, vpisujem moje stringy na x,y, poziciu
    $meno = $this->escape($this->uzivatelia->getMeno($this->escape($this->vydaj['vytvoril_u'])));

    $page->setFont($font, 9)
        ->drawText( strval($cislo_listku) , 440, 776)
        ->drawText($spz, 380, 660)
        ->drawText($dodavatel, 380, 720, 'UTF-8')
        ->drawText($adresa, 380, 700, 'UTF-8')
        ->drawText($ico, 380, 688, 'UTF-8')
        ->drawText($dph, 380, 677, 'UTF-8')
        ->drawText($datum, 200, 598)
        ->drawText($cas, 200, 582)
        ->drawText($typ . ' '. $druh, 390, 598, 'UTF-8')
        ->drawText($meno, 390,583, 'UTF-8')
        ->drawText($sklad . ' ' . $podsklad, 200, 567, 'UTF-8' );

    $page->setFont($font, 12)
        ->drawText( number_format($brutto, 2, ",", " ") , 207, 538)
        ->drawText( number_format($tara, 2, ",", " ") , 338, 538)
        ->drawText( number_format($netto, 2, ",", " ") , 463, 538);



//spodny listok
    $page->setFont($font, 9)
        ->drawText( strval($cislo_listku) , 440, 386)
        ->drawText($spz, 380, 270)
        ->drawText($dodavatel, 380, 331, 'UTF-8')
        ->drawText($adresa, 380, 309, 'UTF-8')
        ->drawText($ico, 380, 297, 'UTF-8')
        ->drawText($dph, 380, 286, 'UTF-8')
        ->drawText($datum, 200, 209)
        ->drawText($cas, 200, 194)
        ->drawText($typ . ' '. $druh, 390, 209, 'UTF-8')
        ->drawText($meno, 390,194, 'UTF-8')
        ->drawText($sklad . ' ' . $podsklad, 200, 179, 'UTF-8' );

    $page->setFont($font, 12)

        ->drawText( number_format($brutto, 2, ",", " ") , 207, 149)
        ->drawText( number_format($tara, 2, ",", " ") , 338, 149)
        ->drawText( number_format($netto, 2, ",", " ") , 463, 149);

    // viem tu premennu $pdf pridat ako novu stranu (append) ale to teraz nie
    // $pdf->pages[] = $page;

    $output = '../public/pdf/'.$cislo_listku.'.pdf';
    $odkaz = substr($output, 9);
    $pdf->save( $output);

}
    // odchytavam zlyhavky cisto len pre kontrolu

catch (Zend_Pdf_Exception $e) {
    die ('PDF error: ' . $e->getMessage());
} catch (Exception $e) {
    die ('Application error: ' . $e->getMessage());
}

// hotovo , mozem linkovat na existujuci dokument .. cisto pre istotu keby cosi zlyhalo
echo '<a id=”pdfDownloadLink” href=" '.$this->baseUrl().$odkaz.' " '.'>Odkaz na PDF</a>';

// ak je vsetko ok, automaticky redirect na pdf
header('Location: '.$this->baseUrl().$odkaz);

?>