
    <?php
    $this->headTitle($this->title);


    $this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
    ?>





    <script type="text/javascript" language="javascript" class="init">


        $(document).ready(function() {
            $('#fancy_table').DataTable( {

                "order": [[ 1, "desc" ]],

                columnDefs: [
                    { "sType": "title-string", "aTargets": [ 9 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
                ],





            initComplete: function () {
                    var api = this.api();
                    var abc = 0;
                    api.columns().indexes().flatten().each( function ( i ) {


                        var column = api.column( i );

                        if (i != abc) {

                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );

                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                        }
                    } );
                }
            } );

        } );


    </script>


    <?php

    $notifikacie     = new Application_Model_Notifikacie();


    $notif_info = $notifikacie->getStatusArray();

    $count_notif = $notif_info['total'];

    $prijmy_w = $notif_info['prijmy_waitings'];
    $prijmy_e = $notif_info['prijmy_errors'];

    ?>


    <p>
    <div class="dropdown left ">
        <a href="#" class="btn-first dropdown-toggle btn btn-success" data-toggle="dropdown">Pridať príjem <b class="caret"></b></a>
        <ul class="dropdown-menu">

            <li><a href="<?php echo $this->baseUrl().'/skladnik/prijmy/addton'?>">Pridať príjem v tonách</a></li>
            <li><a href="<?php echo $this->baseUrl().'/skladnik/prijmy/addm3'?>">Pridať príjem v m<sup>3</sup></a></li>
            <li><a href="<?php echo $this->baseUrl().'/skladnik/prijmy/addprm'?>">Pridať príjem v PRM</a></li>

        </ul>
    </div>

        <a href="<?php echo $this->url(array('controller'=>'prijmy',
            'action'=>'list'));?>" type="button" class="btn btn-info">
            všetky
        </a>

        <a href="<?php echo $this->url(array('controller'=>'prijmy',
            'action'=>'no-errors'));?>" type="button" class="btn btn-success">
            bez chýb
        </a>

        <a href="<?php echo $this->url(array('controller'=>'prijmy',
            'action'=>'errors'));?>" type="button" class="btn btn-danger">
            chyby
        </a>



    </p>


<div id=".col-lg-12"  class="table-responsive">
<table id="fancy_table"  class="table table-striped table-bordered table-hover">



    <thead>
    <tr class="tableizer-firsrow">
<!--    <th>ID</th>-->
<!--        <th>doklad číslo</th>-->
        <TH>detail</TH>
        <th>dátum</th>
    <th>sklad</th>
    <th class="col-podsklad">podsklad</th>
    <th>dodávateľ</th>
    <th>prepravca</th>
<!--    <th>SPZ</th>-->
    <th>tony m</th>
    <th class="col-tony-nadrozmer">tony nadrozmer</th>
    <th>vlhkosť</th>
    <th>číslo dokladu</th>
<!--    <th>t v</th>-->
<!--    <th>m3 m</th>-->
<!--    <th>m3 v</th>-->
<!--    <th>PRM m</th>-->
<!--    <th>PRM v</th>-->

<!--    <th>materiál typ</th>-->
    <th>materiál druh</th>
    <th class="col-stav">stav</th>
<!--    <th class="col-chyba">chyba</th>-->
    <th class="col-upravy">úpravy </th>
    </tr>
    </thead>

    <tfoot>
    <tr>
<!--        <th>ID</th>-->
<!--        <th>doklad číslo</th>-->
        <th></th>
        <th>dátum</th>
        <th>sklad</th>
        <th>podsklad</th>
        <th>dodávateľ</th>
        <th>prepravca</th>
<!--        <th>SPZ</th>-->
        <th>t m</th>
        <th>t nadrozmer</th>
<!--        <th>t v</th>-->
<!--        <th>m3 m</th>-->
<!--        <th>m3 v</th>-->
<!--        <th>PRM m</th>-->
<!--        <th>PRM v</th>-->

<!--        <th>materiál typ</th>-->
        <th>materiál druh</th>
<!--        <th>stav</th>-->
<!--        <th>chyba</th>-->
<!--        <th  >úpravy</th>-->
    </tr>
    </tfoot>

    <tbody>
        <?php foreach($this->prijmy as $prijem) : ?>

            <?php if ($prijem->chyba == 1 ) echo "<tr class='danger'> ";
            else echo   "<tr>";
            ?>

<!--            <td>--><?php //echo $this->escape($prijem->ts_prijmy_id);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->doklad_cislo);?><!--</td>-->
            <TD class="center"><a href="<?php echo $this->url(array('controller'=>'prijmy',
                'action'=>'preview', 'id'=>$prijem->doklad_cislo, 'fromAction' => 'list'));?>">
                     <?php echo '<img src="'.$this->baseUrl().'/images/zobrazit.png" alt="detail">'; ?>
                </a>
</TD>
            <td>

                <?php
                    $date = date('Y/M/d', strtotime($this->escape($prijem->datum_prijmu_d)));
                    echo $date;
                    //echo $this->escape($prijem->datum_prijmu_d);
                ?>
            </td>
            <td><?php echo $this->escape($this->sklady->getSkratka($prijem->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($prijem->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->dodavatelia->getNazov($prijem->dodavatel_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($prijem->prepravca_enum));?></td>
<!--            <td>--><?php //echo $this->escape($prijem->prepravca_spz);?><!--</td>-->
            <td><?php echo number_format($this->escape($prijem->q_tony_merane), 2, ",", " ");?></td>
            <td><?php echo number_format($this->escape($prijem->q_tony_nadrozmer), 2, ",", " ");?></td>
            <td>
                <?php
                    if ($prijem->q_vlhkost == 0.00){
                        echo "-";
                    }else {
                        echo number_format($this->escape($prijem->q_vlhkost), 2, ",", " ") . "%";
                    }
                ?>
            </td>
            <td><?php echo $this->escape($prijem->doklad_cislo);?></td>

<!--            <td>--><?php //echo $this->escape($prijem->q_tony_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_m3_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_m3_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_vypocet);?><!--</td>-->

<!--            <td>--><?php //echo $this->escape($this->materialyTypy->getNazov($prijem->material_typ_enum));?><!--</td>-->
            <td><?php echo $this->escape($this->materialyDruhy->getNazov($prijem->material_druh_enum));?></td>
            <td>
                <?php

            if  (strcmp('schvalene', $this->escape($this->transakcieStavy->getNazov($prijem->stav_transakcie)) ) == 0 ) {

//                    echo '<img src="'.$this->baseUrl().'/images/schvalene.png" alt="schvalene">';
                echo '<div class="schvalene"></div>';
            }
            else if (strcmp('caka na schvalenie', $this->escape($this->transakcieStavy->getNazov($prijem->stav_transakcie)) ) == 0 ) {

//                    echo '<img src="'.$this->baseUrl().'/images/caka.png" alt="caka na schvalenie">';
                echo '<div class="caka"></div>';
            }
            else {

//                    echo '<img src="'.$this->baseUrl().'/images/zrusene.png" alt="zrusene">';
                echo '<div class="zrusene"></div>';
            }
            ?>

               <?php //echo $this->escape($this->transakcieStavy->getNazov($prijem->stav_transakcie));?>

            </td>
<!--            <td>-->
<!--                --><?php
//                    if ($this->escape($prijem->chyba) == 1)
//                        {echo "áno";}
//                    else {echo "nie";}
//                    ?>
<!--            </td>-->
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Prijmy', 'action'=>'print', 'id'=>$prijem->ts_prijmy_id, 'cislo_listku'=>$prijem->doklad_cislo, 'fromAction' => 'list',
                    'spz'=>$prijem->prepravca_spz)) ;?>" target="_blank">
                    <?php echo '<img src="'.$this->baseUrl().'/images/tlacit.png" alt="tlacit">'; ?>
                </a>

                <?php
                    if ($prijem->chyba == 0){
                ?>
                <a href="<?php echo $this->url(array('controller'=>'prijmy', 'action'=>'mark-as-error', 'module'=>'skladnik', 'id'=>$prijem->ts_prijmy_id, 'fromAction' => 'no-errors'));?>">

                    <?php echo '<img src="'.$this->baseUrl().'/images/oznacit.png" alt="oznacit">'; ?>

                </a>
                <?php } else{
                        echo $this->chyba;
                    }?>





            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</div>