<h2 >Príjmy - vytvoriť nový</h2>
<!--<hr>-->
<div class="col-lg-5">
    <div class="panel panel-green">
        <div class="panel-heading">
            <h3 class="panel-title">Detail transakcie </h3>
        </div>
        <div class="panel-body">


            <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                  method="<?php echo $this->escape($this->form->getMethod()) ?>"
                  enctype="multipart/form-data" class="normal">


                    <?php echo $this->form->ts_prijmy_id; ?>




            <div class="row">
                <fieldset>
<!--                    <legend>Dátum príjmu</legend>-->

                    <div class="col-lg-6">
<!--                        Dátum:-->
                        <?php echo $this->form->datum_prijmu_d; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>
            <!---->
            <div class="row">
                <fieldset>
                    <legend>Sklady</legend>
                    <div class="col-lg-6">
<!--                        Sklad:-->
                        <?php echo $this->form->sklad_enum; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
<!--                        Podsklad:-->
                        <?php echo $this->form->podsklad_enum; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

            <!--        -->
            <div class="row">
                <fieldset>
                    <legend>Dodanie</legend>
                    <div class="col-lg-6">
<!--                        Dodávateľ:-->
                        <?php echo $this->form->dodavatel_enum; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
<!--                        Prepravca:-->
                        <?php echo $this->form->prepravca_enum; // render the user name field here ?>
                    </div>
            </div>
            <!--        -->
            <div class="row">
                <div class="col-lg-6">
<!--                    ŠPZ:-->
                    <?php echo $this->form->prepravca_spz; // render the user name field here ?>
                </div>
                </fieldset>
            </div>
            <!---->

<!--                cast pre prepocty -->
            <?php

                $merneJednotky = new Application_Model_DbTable_MerneJednotky();

            $moznosti = $merneJednotky->getPrepoctyArray(5,1,2);

//            var_dump($moznosti);
            ?>
<!--                koniec prepoctov .. rozparsovane -->
            <div class="row">
                <fieldset>
                    <legend>Množstvo</legend>
                    <div class="col-lg-6">
<!--                        Netto:-->
                        <?php echo $this->form->q_tony_merane; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Brutto:-->
                        <?php echo $this->form->q_tony_nadrozmer; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

                <div class="row">
                    <div class="col-lg-6">

                        <?php echo $this->form->q_tony_brutto; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">

                        <?php echo $this->form->q_m3_merane; // render the user name field here ?>
                    </div>


                </div>

                <div class="row">

                    <div class="col-lg-6">

                        <?php echo $this->form->q_tony_tara; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">

                        <?php echo $this->form->q_prm_merane; // render the user name field here ?>
                    </div>

                </div>


            <div class="row">
                <fieldset>
                    <legend>Materiál</legend>
                    <div class="col-lg-6">
<!--                        Typ:-->
                        <?php echo $this->form->material_typ_enum; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Druh:-->
                        <?php echo $this->form->material_druh_enum; // render the user name field here ?>
                    </div>

            </div>


            <div class="row">
                <fieldset>
                    <legend>Doplňujúce informácie</legend>
                    <div class="col-lg-6">
<!--                        Stav:-->
                        <?php echo $this->form->stav_transakcie; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Chyba:-->
                        <?php echo $this->form->chyba; // render the user name field here ?>
                    </div>
            </div>

            <div class="row">

                <div class="col-lg-12">
<!--                    Poznámka:-->
                    <?php echo $this->form->poznamka; // render the user name field here ?>
                </div>
                </fieldset>
            </div>



                <div class="row">

                    <div class="col-lg-6">

                        <?php echo $this->form->potvrdzujuceTlacidlo; // render the user name field here ?>

                    </div>


                    <div class="col-lg-6">
                            <dt>&nbsp;</dt>
                        <a href="<?php
                        //pageManager
                        echo $this->url(array(
                            'controller' => $_SESSION['pageManager']['lastPageParameters']['controller'],
                            'action' => $_SESSION['pageManager']['lastPageParameters']['action']
                        ), null, true) ?>"  type="button" class="btn btn-warning">Späť</a>

                    </div>
                </div>
<!--                --><?php //echo $this->form->doklad_typ_enum; // render the user name field here ?>
        </form>




<script>
    $(document).ready(function(){
        $(".input").keyup(function(){
            var tonym = +$(".tonym").val();
            var tonyv = +$(".tonyv").val();

            var prmm = +$(".prmm").val();
            var prmv = +$(".prmv").val();

            $(".tonyv").val(2*prmm);
            $(".prmv").val((1/2)*tonym);


//            $("#result").val(val1+val2);
        });
    });

</script>
<!---->
<!---->
<!--tony merane <input type="text" class="input tonym"> <br>-->
<!--tony vypocet <input type="text" class="input tonyv" disabled><br>-->
<!--<br>-->
<!--prm merane <input type="text" class="input prmm"><br>-->
<!--prm vypocet <input type="text" class="input prmv" disabled><br>-->
<!---->



