<h2 >Príjmy - vytvoriť nový</h2>
<!--<hr>-->



<script>


    function isEmpty(str){

        if(document.getElementById(str).value == "")
        {
            return true;
        }
        return false;

    }

    $(document).ready(function(){


        $(".in").keyup(function(){

            var tonym = +$("#q_tony_merane").val();
            var tonyb = +$("#q_tony_brutto").val();

            var tonyt = +$("#q_tony_tara").val();
            var m3 = +$("#q_m3_merane").val();
            var prm = +$("#q_prm_merane").val();

            var tony2m3 = 2;
            var tony2prm = 3;

            var m32tony = 0.5;
            var m32prm = 5;

            var prm2tony = 1.5;
            var prm2m3 = 2.5;

            var nula = "";


//            vyplnam tony
            if ( !isEmpty("q_tony_brutto") || !isEmpty("q_tony_tara") || !isEmpty("q_tony_nadrozmer")
            && ( isEmpty("q_prm_merane") || isEmpty("q_m3_merane") )   ) {
//            disable na prm a m3
                document.getElementById('q_m3_merane').readOnly = true;
                document.getElementById('q_prm_merane').readOnly = true;

                $("#q_tony_merane").val(tonyb - tonyt);

                $("#q_prm_merane").val( (tonyb - tonyt ) * tony2prm);
                $("#q_m3_merane").val( (tonyb - tonyt ) * tony2m3);
            }

//          nevyplnam tony
            if ( isEmpty("q_tony_brutto") && isEmpty("q_tony_tara") && isEmpty("q_tony_nadrozmer")
                && !isEmpty("q_m3_merane") &&  !isEmpty("q_prm_merane") ) {
//            disable na prm a m3
                document.getElementById('q_m3_merane').readOnly = false;
                document.getElementById('q_prm_merane').readOnly = false;

                $("#q_tony_merane").val(nula);
                $("#q_prm_merane").val( nula);
                $("#q_m3_merane").val( nula );

            }



//            vyplnam m3
            if ( !isEmpty("q_m3_merane") && isEmpty("q_tony_brutto") && isEmpty("q_tony_tara") &&
                isEmpty("q_tony_brutto") && isEmpty("q_tony_nadrozmer") && isEmpty("q_prm_merane")) {
//            disable na prm a tony
                document.getElementById('q_tony_brutto').readOnly = true;
                document.getElementById('q_tony_tara').readOnly = true;
                document.getElementById('q_tony_merane').readOnly = true;
                document.getElementById('q_tony_nadrozmer').readOnly = true;
                document.getElementById('q_prm_merane').readOnly = true;

                $("#q_tony_merane").val( m3 * m32tony);
                $("#q_prm_merane").val( m3 * m32prm);
            }

            if ( isEmpty("q_m3_merane") && isEmpty("q_tony_brutto") && isEmpty("q_tony_tara") &&
                 isEmpty("q_tony_nadrozmer") && isEmpty("q_prm_merane") ) {
//            disable na prm a tony
                document.getElementById('q_tony_brutto').readOnly = false;
                document.getElementById('q_tony_tara').readOnly = false;
                document.getElementById('q_tony_merane').readOnly = false;
                document.getElementById('q_tony_nadrozmer').readOnly = false;
                document.getElementById('q_prm_merane').readOnly = false ;

                $("#q_tony_merane").val(nula);
                $("#q_prm_merane").val( nula);
                $("#q_m3_merane").val( nula );

            }
            //vyplnam prm
            if ( !isEmpty("q_prm_merane") && isEmpty("q_tony_brutto") && isEmpty("q_tony_tara") &&
                isEmpty("q_tony_brutto") && isEmpty("q_tony_nadrozmer") && isEmpty("q_m3_merane")) {
//            disable na m3 a tony
                document.getElementById('q_tony_brutto').readOnly = true;
                document.getElementById('q_tony_tara').readOnly = true;
                document.getElementById('q_tony_merane').readOnly = true;
                document.getElementById('q_tony_nadrozmer').readOnly = true;
                document.getElementById('q_m3_merane').readOnly = true ;


                $("#q_tony_merane").val( prm * prm2tony);
//                $("#q_m3_merane").val( m3 * m32tony);
            }

            if ( isEmpty("q_prm_merane") && isEmpty("q_tony_brutto") && isEmpty("q_tony_tara") &&
                isEmpty("q_tony_brutto") && isEmpty("q_tony_nadrozmer") && isEmpty("q_m3_merane") ) {
//            disable na prm a tony
                document.getElementById('q_tony_brutto').readOnly = false;
                document.getElementById('q_tony_tara').readOnly = false;
                document.getElementById('q_tony_merane').readOnly = false;
                document.getElementById('q_tony_nadrozmer').readOnly = false;
                document.getElementById('q_m3_merane').readOnly = false ;

                $("#q_tony_merane").val(nula);
                $("#q_prm_merane").val( nula);
                $("#q_m3_merane").val( nula );
            }



        });
    });

</script>

<div class="col-lg-5">
    <div class="panel panel-green">
        <div class="panel-heading">
            <h3 class="panel-title">Detail transakcie </h3>
        </div>
        <div class="panel-body">


            <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                  method="<?php echo $this->escape($this->form->getMethod()) ?>"
                  enctype="multipart/form-data" class="normal">


                    <?php echo $this->form->ts_prijmy_id; ?>




            <div class="row">
                <fieldset>
<!--                    <legend>Dátum príjmu</legend>-->

                    <div class="col-lg-6">
<!--                        Dátum:-->
                        <?php echo $this->form->datum_prijmu_d; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>
            <!---->
            <div class="row">
                <fieldset>
                    <legend>Sklady</legend>
                    <div class="col-lg-6">
<!--                        Sklad:-->
                        <?php echo $this->form->sklad_enum; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
<!--                        Podsklad:-->
                        <?php echo $this->form->podsklad_enum; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

            <!--        -->
            <div class="row">
                <fieldset>
                    <legend>Dodanie</legend>
                    <div class="col-lg-6">
<!--                        Dodávateľ:-->
                        <?php echo $this->form->dodavatel_enum; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">
<!--                        Prepravca:-->
                        <?php echo $this->form->prepravca_enum; // render the user name field here ?>
                    </div>
            </div>
            <!--        -->
            <div class="row">
                <div class="col-lg-6">
<!--                    ŠPZ:-->
                    <?php echo $this->form->prepravca_spz; // render the user name field here ?>
                </div>
                </fieldset>
            </div>
            <!---->

<!--                cast pre prepocty -->
            <?php

                $merneJednotky = new Application_Model_DbTable_MerneJednotky();

            $moznosti = $merneJednotky->getPrepoctyArray(5,1,2);

//            var_dump($moznosti);
            ?>
<!--                koniec prepoctov .. rozparsovane -->
            <div class="row">
                <fieldset>
                    <legend>Množstvo</legend>
                    <div class="col-lg-6">
<!--                        Netto:-->
                        <?php echo $this->form->q_tony_merane; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Brutto:-->
                        <?php echo $this->form->q_tony_nadrozmer; // render the user name field here ?>
                    </div>
                </fieldset>
            </div>

                <div class="row">
                    <div class="col-lg-6">

                        <?php echo $this->form->q_tony_brutto; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">

                        <?php echo $this->form->q_m3_merane; // render the user name field here ?>
                    </div>


                </div>

                <div class="row">

                    <div class="col-lg-6">

                        <?php echo $this->form->q_tony_tara; // render the user name field here ?>
                    </div>

                    <div class="col-lg-6">

                        <?php echo $this->form->q_prm_merane; // render the user name field here ?>
                    </div>

                </div>


            <div class="row">
                <fieldset>
                    <legend>Materiál</legend>
                    <div class="col-lg-6">
<!--                        Typ:-->
                        <?php echo $this->form->material_typ_enum; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Druh:-->
                        <?php echo $this->form->material_druh_enum; // render the user name field here ?>
                    </div>

            </div>


            <div class="row">
                <fieldset>
                    <legend>Doplňujúce informácie</legend>
                    <div class="col-lg-6">
<!--                        Stav:-->
                        <?php echo $this->form->stav_transakcie; // render the user name field here ?>
                    </div>
                    <div class="col-lg-6">
<!--                        Chyba:-->
                        <?php echo $this->form->chyba; // render the user name field here ?>
                    </div>
            </div>

            <div class="row">

                <div class="col-lg-12">
<!--                    Poznámka:-->
                    <?php echo $this->form->poznamka; // render the user name field here ?>
                </div>
                </fieldset>
            </div>



                <div class="row">

                    <div class="col-lg-6">

                        <?php echo $this->form->potvrdzujuceTlacidlo; // render the user name field here ?>

                    </div>


                    <div class="col-lg-6">
                            <dt>&nbsp;</dt>
                        <a href="<?php
                        //pageManager
                        echo $this->url(array(
                            'controller' => $_SESSION['pageManager']['lastPageParameters']['controller'],
                            'action' => $_SESSION['pageManager']['lastPageParameters']['action']
                        ), null, true) ?>"  type="button" class="btn btn-warning">Späť</a>

                    </div>
                </div>
<!--                --><?php //echo $this->form->doklad_typ_enum; // render the user name field here ?>
        </form>



