
<?php
$this->title = "Zmazať Príjem";
$this->headTitle($this->title);

?>
<p>Naozaj chcete zmazať príjem <?php echo $this->prijem['doklad_cislo'];?>?</p>

<div class="row">




        <div class="col-lg-2">
            datum prijmu
            <?php echo $this->prijem['datum_prijmu_d']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            sklad
            <?php echo $this->ciselniky['skladyModel']->getNazov($this->prijem['sklad_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            podsklad
            <?php echo $this->ciselniky['podskladyModel']->getNazov($this->prijem['podsklad_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            dodavatel
            <?php echo $this->ciselniky['dodavateliaModel']->getNazov($this->prijem['dodavatel_enum']); // render the user name field here ?>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-2">
            prepravca
            <?php echo $this->ciselniky['prepravciModel']->getNazov($this->prijem['prepravca_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            spz
            <?php echo $this->prijem['prepravca_spz']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            tony netto
            <?php echo $this->prijem['q_tony_merane']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            tony nadrozmer
            <?php echo $this->prijem['q_tony_nadrozmer']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            PRM
            <?php echo $this->prijem['q_prm_merane']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            m3
            <?php echo $this->prijem['q_m3_merane']; // render the user name field here ?>
        </div>
    </div>



    <div class="row">

        <div class="col-lg-2">
            material typ
            <?php echo $this->ciselniky['materialyTypyModel']->getNazov($this->prijem['material_typ_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            material druh
            <?php echo $this->ciselniky['materialyDruhyModel']->getNazov($this->prijem['material_druh_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            chyba
            <?php echo $this->prijem['chyba']; // render the user name field here ?>
        </div>
    </div>


    <div class="row">

        <div class="col-lg-2">
            poznamka
            <?php echo $this->prijem['poznamka']; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            stav
            <?php echo $this->ciselniky['transakcieStavyModel']->getNazov($this->prijem['stav_transakcie']); // render the user name field here ?>
        </div>

    </div>









<form action="<?php echo $this->url(array('action'=>'delete')); ?>"
      method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->prijem['ts_prijmy_id']; ?>" />
        <input type="submit" name="del" value="Yes" class="btn btn-success"/>
        <input type="submit" name="del" value="No" class="btn btn-warning"/>
    </div>
</form>