<?php
$this->title = "Edit prijem";
$this->headTitle($this->title);
//print_r($this->data);
//echo $this->form;
?>

<form action="<?php echo $this->escape($this->form->getAction()) ?>"
      method="<?php echo $this->escape($this->form->getMethod()) ?>"
      enctype="multipart/form-data">
    <div class="row">

        <?php echo $this->form->ts_prijmy_id; ?>


        <div class="col-lg-2">
            <?php echo $this->form->datum_prijmu_d; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->sklad_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->podsklad_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->dodavatel_enum; // render the user name field here ?>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-2">
            <?php echo $this->form->prepravca_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->prepravca_spz; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->q_tony_merane; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->q_tony_nadrozmer; // render the user name field here ?>
        </div>
    </div>



    <div class="row">

        <div class="col-lg-2">
            <?php echo $this->form->doklad_typ_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->material_typ_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->material_druh_enum; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->chyba; // render the user name field here ?>
        </div>
    </div>


    <div class="row">

        <div class="col-lg-2">
            <?php echo $this->form->poznamka; // render the user name field here ?>
        </div>
        <div class="col-lg-2">
            <?php echo $this->form->stav_transakcie; // render the user name field here ?>
        </div>

    </div>


    <div class="row">


        <div class="col-lg-2">
            <?php echo $this->form->potvrdzujuceTlacidlo; // render the user name field here ?>
        </div>

        <div class="col-lg-2">
            <dt>&nbsp;</dt>
            <a href="<?php echo $this->url(array(
                'controller' => 'prijmy',
                'action' => 'list'
            ), null, true) ?>"  type="button" class="btn btn-warning">Späť</a>
        </div>
    </div>

</form>
