<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/table_features.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/fancy_table.js');

$notifikacie     = new Application_Model_Notifikacie();
$notif_info = $notifikacie->getStatusArray();
$count_notif = $notif_info['total'];
$prijmy_w = $notif_info['prijmy_waitings'];
$prijmy_e = $notif_info['prijmy_errors'];

$controller = 'prijmy';
$this->prijmybuttons($this,$prijmy_w,$prijmy_e,$controller);

?>


<div id=".col-lg-12"  class="table-responsive">
    <table id="fancy_table"  class="table table-striped table-hover">

        <thead>
        <tr class="tableizer-firsrow">
            <!--    <th>ID</th>-->
            <!--        <th>doklad číslo</th>-->
            <TH class="no-print">Detail</TH>
            <th>Dátum</th>
            <th>Sklad</th>
            <th class="col-podsklad">Podsklad</th>
            <th>Dodávateľ</th>
            <th>Prepravca</th>
            <!--    <th>SPZ</th>-->
            <th>Tony</th>
            <th>m<sup>3</sup></th>
            <th>Vlhkosť</th>
            <th class="col-tony-nadrozmer">Nadrozmer</th>
            <th>Doklad</th>
            <!--    <th>t v</th>-->

            <!--    <th>m3 v</th>-->
            <!--    <th>PRM m</th>-->
            <!--    <th>PRM v</th>-->

            <!--    <th>materiál typ</th>-->
            <th>Materiál</th>
            <th class="col-stav">Stav</th>
            <!--    <th class="col-chyba">chyba</th>-->
            <th class="col-upravy no-print">Úpravy</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <!--        <th>ID</th>-->
            <!--        <th>doklad číslo</th>-->
            <th></th>
            <th>datum</th>
            <th>sklad</th>
            <th>podsklad</th>
            <th>dod</th>
            <th>prepravca</th>
            <!--        <th>SPZ</th>-->
            <th>t m</th>
            <th>t nadrozmer</th>
            <!--        <th>t v</th>-->
                    <th>m3 m</th>
            <!--        <th>m3 v</th>-->
            <!--        <th>PRM m</th>-->
            <!--        <th>PRM v</th>-->

            <!--        <th>materiál typ</th>-->
            <th>material druh</th>
                    <th></th>
                    <th>chyba</th>
<!--                    <th  >úpravy</th>-->
<!--            <th></th>-->
<!--            <th></th>-->

        </tr>
        </tfoot>

        <tbody>
        <?php foreach($this->prijmy as $prijem) : ?>

            <?php if ($prijem->chyba == 1 ) echo "<tr class='danger'> ";
            else echo   "<tr>";
            ?>

            <TD class="center no-print"><a href="<?php echo $this->url(array('controller'=>'prijmy',
                'action'=>'preview', 'id'=>$prijem->doklad_cislo, 'fromAction' => 'errors'));?>">
                     <i class="fa fa-eye"></i>
                </a>
            </TD>
            <td>

                <?php
            $date = date('Y/M/d', strtotime($this->escape($prijem->datum_prijmu_d)));
            echo $date;
            ?>
            </td>
            <td><?php echo $this->escape($this->sklady->getSkratka($prijem->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($prijem->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->dodavatelia->getNazov($prijem->dodavatel_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($prijem->prepravca_enum));?></td>
<!--            <td>--><?php //echo $this->escape($prijem->prepravca_spz);?><!--</td>-->
      <td class="tonaz"><?php echo number_format($this->escape($prijem->q_tony_merane), 2, ",", " ");?></td>
            <td class="m3"><?php echo number_format($this->escape($prijem->q_m3_merane), 2, ",", " ");?></td>
            <td class="vlhkost">
                <?php
            if ($prijem->q_vlhkost == 0.00){
                echo "-";
            }else {
                echo number_format($this->escape($prijem->q_vlhkost), 2, ",", " "). "%";

            }
            ?>
            </td>
            <td><?php echo number_format($this->escape($prijem->q_tony_nadrozmer), 2, ",", " ");?></td>
            <td><?php echo $this->escape($prijem->doklad_cislo);?></td>
            <td class="center"><?php echo $this->escape($this->materialyDruhy->getNazov($prijem->material_druh_enum));?></td>
            <td>
           <?php
            $this->stavy($prijem);
            ?>
            </td>

            <td class="no-print">

                <?php
            $skladID = $prijem->sklad_enum;
            $merna_jednotka = $this->sklady->getMernaJednotka($skladID);

            $this->tlacbuttons($this,$merna_jednotka,$prijem->ts_prijmy_id,$controller);
            ?>

            </td>

        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div id="tonaz">   </div>
    <div id="m3">   </div>
    <div id="priemer"> </div>

</div>