
<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
?>





<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#fancy_table').DataTable( {
            "order": [[ 1, "desc" ]],
            columnDefs: [
                { "sType": "title-string", "aTargets": [ 12 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
            ],
            initComplete: function () {
                var api = this.api();
                var abc = 0;
                api.columns().indexes().flatten().each( function ( i ) {
                    var column = api.column( i );
                    if (i != abc) {
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    }
                } );
            }
        } );
    } );
</script>
<!--
    <div class="alert alert-dismissable alert-info">
        <a href="<?php echo $this->url(array('controller'=>'prijmy',
    'action'=>'add', "fromController" => 'prijmy', "fromAction" => 'list'));?>">
            <?php echo '<img src="'.$this->baseUrl().'/images/pridat.png" alt="pridat">'; ?>
            Pridať záznam</a>
        <a href="<?php echo '../' ?>" type="button" class="btn btn-warning right">Späť</a>
    </div>
-->

<?php
$notifikacie     = new Application_Model_Notifikacie();
$notif_info = $notifikacie->getStatusArray();
$count_notif = $notif_info['total'];
$prijmy_w = $notif_info['prijmy_waitings'];
$prijmy_e = $notif_info['prijmy_errors'];
?>


<p>
    <a href="<?php echo $this->url(array('controller'=>'Prijmy',
        'action'=>'add', 'fromAction' => 'list'));?>" type="button" class="btn btn-success">
        Pridať príjem
    </a>
    <a href="<?php echo $this->url(array('controller'=>'Prijmy',
        'action'=>'list'));?>" type="button" class="btn btn-info">
        Všetky príjmy
    </a>



    <?php if ($prijmy_w >0) { ?>
        <a href="<?php echo $this->url(array(
            'controller' => 'prijmy',
            'action' => 'waitings'
        ), null, true) ?>" type="button" class="btn btn-warning">Na schválenie (<?php echo $prijmy_w; ?>) </a>
    <?php }
    if ($prijmy_e > 0) {
        ?>
        <a href="<?php echo $this->url(array(
            'controller' => 'prijmy',
            'action' => 'errors'
        ), null, true) ?>" type="button" class="btn btn-danger"> Chybné (<?php echo $prijmy_e   ; ?>) </a>
    <?php } ?>
</p>


<div id=".col-lg-12"  class="table-responsive">
    <table id="fancy_table"  class="table table-striped table-hover">



        <thead>
        <tr class="tableizer-firsrow">
            <!--    <th>ID</th>-->
            <!--        <th>doklad číslo</th>-->
            <TH>Detail</TH>
            <th>Dátum</th>
            <th>Sklad</th>
            <th class="col-podsklad">Podsklad</th>
            <th>Dodávateľ</th>
            <th>Prepravca</th>
            <!--    <th>SPZ</th>-->
            <th>Tony</th>
            <th>m<sup>3</sup></th>
            <th>Vlhkosť</th>
            <th class="col-tony-nadrozmer">Nadrozmer</th>
            <th>Doklad</th>
            <!--    <th>t v</th>-->

            <!--    <th>m3 v</th>-->
            <!--    <th>PRM m</th>-->
            <!--    <th>PRM v</th>-->

            <!--    <th>materiál typ</th>-->
            <th>Materiál</th>
            <th class="col-stav">Stav</th>
            <!--    <th class="col-chyba">chyba</th>-->
            <th class="col-upravy">Úpravy</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <!--        <th>ID</th>-->
            <!--        <th>doklad číslo</th>-->
            <th></th>
            <th>datum</th>
            <th>sklad</th>
            <th>podsklad</th>
            <th>dod</th>
            <th>prepravca</th>
            <!--        <th>SPZ</th>-->
            <th>t m</th>
            <th>t nadrozmer</th>
            <!--        <th>t v</th>-->
                    <th>m3 m</th>
            <!--        <th>m3 v</th>-->
            <!--        <th>PRM m</th>-->
            <!--        <th>PRM v</th>-->

            <!--        <th>materiál typ</th>-->
            <th>material druh</th>
                    <th></th>
                    <th>chyba</th>
<!--                    <th  >úpravy</th>-->
<!--            <th></th>-->
<!--            <th></th>-->

        </tr>
        </tfoot>

        <tbody>
        <?php foreach($this->prijmy as $prijem) : ?>

            <?php if ($prijem->chyba == 1 ) echo "<tr class='danger'> ";
            else echo   "<tr>";
            ?>

<!--            <td>--><?php //echo $this->escape($prijem->ts_prijmy_id);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->doklad_cislo);?><!--</td>-->
            <TD class="center">
                <a href="<?php echo $this->url(array('controller'=>'prijmy',
                    'action'=>'preview', 'id'=>$prijem->doklad_cislo, 'fromAction' => 'list'));?>">
                    <i class="fa fa-eye"></i>
                    <!--                     --><?php //echo '<img src="'.$this->baseUrl().'/images/zobrazit.png" alt="detail">'; ?>
                </a>
            </TD>
            <td>

                <?php
            $date = date('Y/M/d', strtotime($this->escape($prijem->datum_prijmu_d)));
            echo $date;
            //echo $this->escape($prijem->datum_prijmu_d);
            ?>
            </td>
            <td><?php echo $this->escape($this->sklady->getSkratka($prijem->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($prijem->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->dodavatelia->getNazov($prijem->dodavatel_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($prijem->prepravca_enum));?></td>
<!--            <td>--><?php //echo $this->escape($prijem->prepravca_spz);?><!--</td>-->
            <td><?php echo number_format($this->escape($prijem->q_tony_merane), 2, ",", " ");?></td>
            <td><?php echo number_format($this->escape($prijem->q_m3_merane), 2, ",", " ");?></td>
            <td>
                <?php
            if ($prijem->q_vlhkost == 0.00){
                echo "-";
            }else {
                echo number_format($this->escape($prijem->q_vlhkost), 2, ",", " ") . "%";
            }
            ?>
            </td>
            <td><?php echo number_format($this->escape($prijem->q_tony_nadrozmer), 2, ",", " ");?></td>
            <td><?php echo $this->escape($prijem->doklad_cislo);?></td>

<!--            <td>--><?php //echo $this->escape($prijem->q_tony_vypocet);?><!--</td>-->

<!--            <td>--><?php //echo $this->escape($prijem->q_m3_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_vypocet);?><!--</td>-->

<!--            <td>--><?php //echo $this->escape($this->materialyTypy->getNazov($prijem->material_typ_enum));?><!--</td>-->
            <td><?php echo $this->escape($this->materialyDruhy->getNazov($prijem->material_druh_enum));?></td>
            <td>
               <?php
            if  ( $prijem->stav_transakcie == 2 ) {
//                    echo '<img src="'.$this->baseUrl().'/images/schvalene.png" alt="schvalene">';
                echo '<i class="fa fa-check-circle-o"></i>';
            }
            else if ( $prijem->stav_transakcie == 1) {
//                    echo '<img src="'.$this->baseUrl().'/images/caka.png" alt="caka na schvalenie">';
//                echo '<div class="caka"></div>';
                echo '<i class="fa fa-clock-o"></i>';
            }
            else {
//                    echo '<img src="'.$this->baseUrl().'/images/zrusene.png" alt="zrusene">';
                echo '<i class="fa fa-times-circle-o"></i>';
            }
            ?>

            <?php //echo $this->escape($this->transakcieStavy->getNazov($prijem->stav_transakcie));?>

            </td>
<!--            <td>-->
<!--                --><?php
//                    if ($this->escape($prijem->chyba) == 1)
//                        {echo "áno";}
//                    else {echo "nie";}
//                    ?>
<!--            </td>-->
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Prijmy', 'action'=>'delete', 'id'=>$prijem->ts_prijmy_id, 'fromAction' => 'list'));?>"><i class="fa fa-trash-o"></i></a>
<!--                    --><?php //echo '<img src="'.$this->baseUrl().'/images/zmazat.png" alt="zmazat">'; ?>


                <a href="<?php echo $this->url(array('controller'=>'Prijmy', 'action'=>'edit', 'id'=>$prijem->ts_prijmy_id, 'fromAction' => 'list'));?>"><i class="fa fa-pencil-square-o"></i></a>
<!--                    --><?php //echo '<img src="'.$this->baseUrl().'/images/upravit.png" alt="upravit">'; ?>
                <?php
                $skladID = $prijem->sklad_enum;
                $merna_jednotka = $this->sklady->getMernaJednotka($skladID);

                  if ($merna_jednotka == 1 )
                                echo '<a href="'.$this->url(array("controller"=>"Prijmy", "action"=>"printton", "id"=>$prijem->ts_prijmy_id, "fromAction" => "list",
                                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
//                <!--                    printton-->
                            ?>

                <?php  if ($merna_jednotka == 2 )
                                echo '<a href="'.$this->url(array("controller"=>"Prijmy", "action"=>"printprm", "id"=>$prijem->ts_prijmy_id, "fromAction" => "list",
                                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
//                <!--                   printprm-->
                                ?>
                <?php  if ($merna_jednotka == 3 )
                                echo '<a href="'.$this->url(array("controller"=>"Prijmy", "action"=>"printm3", "id"=>$prijem->ts_prijmy_id, "fromAction" => "list",
                                    )).'" target="_blank"><i class="fa fa-print"></i></a>'
//                <!--                    printm3-->
//                                    <img src="'.$this->baseUrl().'/images/tlacit.png" alt="tlacit">
//                                ?>

            </td>

        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>