
    <?php
    $this->headTitle($this->title);


    $this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
    ?>


    <script type="text/javascript" language="javascript" class="init">


        $(document).ready(function() {
            $('#fancy_table').DataTable( {
                initComplete: function () {
                    var api = this.api();

                    api.columns().indexes().flatten().each( function ( i ) {
                        var column = api.column( i );
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );

                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    } );
                }
            } );
        } );


    </script>

    <div class="alert alert-dismissable alert-warning">
        <a href="<?php echo $this->url(array('controller'=>'prijmy',
            'action'=>'add'));?>">Pridať záznam</a>
    </div>


<div id=".col-lg-12"  class="table-responsive">
<table id="fancy_table"  class="table table-striped table-bordered table-hover">

    <thead>
    <tr class="tableizer-firsrow">
<!--    <th>ID</th>-->
        <th>doklad číslo</th>
        <th>dátum</th>
    <th>sklad</th>
    <th>podsklad</th>
    <th>dodávateľ</th>
    <th>prepravca</th>
    <th>SPZ</th>
    <th>t m</th>
    <th>t nadrozmer</th>
<!--    <th>t v</th>-->
<!--    <th>m3 m</th>-->
<!--    <th>m3 v</th>-->
<!--    <th>PRM m</th>-->
<!--    <th>PRM v</th>-->

    <th>materiál typ</th>
    <th>materiál druh</th>
    <th>stav</th>
    <th>chyba</th>
    <th>úpravy</th>
    </tr>
    </thead>

    <tfoot>
    <tr>
<!--        <th>ID</th>-->
        <th>doklad číslo</th>
        <th>dátum</th>
        <th>sklad</th>
        <th>podsklad</th>
        <th>dodávateľ</th>
        <th>prepravca</th>
        <th>SPZ</th>
        <th>t m</th>
        <th>t nadrozmer</th>
<!--        <th>t v</th>-->
<!--        <th>m3 m</th>-->
<!--        <th>m3 v</th>-->
<!--        <th>PRM m</th>-->
<!--        <th>PRM v</th>-->

        <th>materiál typ</th>
        <th>materiál druh</th>
        <th>stav</th>
        <th>chyba</th>
        <th>úpravy</th>
    </tr>
    </tfoot>

    <tbody>
        <?php foreach($this->prijmy as $prijem) : ?>
        <tr>
<!--            <td>--><?php //echo $this->escape($prijem->ts_prijmy_id);?><!--</td>-->
            <td><?php echo $this->escape($prijem->doklad_cislo);?></td>
            <td>
                <?php
                    $date = date('d.m.Y', strtotime($this->escape($prijem->datum_prijmu_d)));
                    echo $date;
                    //echo $this->escape($prijem->datum_prijmu_d);
                ?>
            </td>
            <td><?php echo $this->escape($this->sklady->getNazov($prijem->sklad_enum));?></td>
            <td><?php echo $this->escape($this->podsklady->getNazov($prijem->podsklad_enum));?></td>
            <td><?php echo $this->escape($this->dodavatelia->getNazov($prijem->dodavatel_enum));?></td>
            <td><?php echo $this->escape($this->prepravci->getNazov($prijem->prepravca_enum));?></td>
            <td><?php echo $this->escape($prijem->prepravca_spz);?></td>
            <td><?php echo $this->escape($prijem->q_tony_merane);?></td>
            <td><?php echo $this->escape($prijem->q_tony_nadrozmer);?></td>
<!--            <td>--><?php //echo $this->escape($prijem->q_tony_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_m3_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_m3_vypocet);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_merane);?><!--</td>-->
<!--            <td>--><?php //echo $this->escape($prijem->q_prm_vypocet);?><!--</td>-->

            <td><?php echo $this->escape($this->materialyTypy->getNazov($prijem->material_typ_enum));?></td>
            <td><?php echo $this->escape($this->materialyDruhy->getNazov($prijem->material_druh_enum));?></td>
            <td><?php echo $this->escape($this->transakcieStavy->getNazov($prijem->stav_transakcie));?></td>
            <td>
                <?php
                    if ($this->escape($prijem->chyba) == 1)
                        {echo "áno";}
                    else {echo "nie";}

                        ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Prijmy',
                    'action'=>'delete', 'id'=>$prijem->ts_prijmy_id));?>">Zmazať</a>

                <a href="<?php echo $this->url(array('controller'=>'Prijmy',
                    'action'=>'edit', 'id'=>$prijem->ts_prijmy_id));?>">Upraviť</a>

                <a href="<?php echo $this->url(array('controller'=>'Prijmy',
                    'action'=>'print', 'id'=>$prijem->ts_prijmy_id, 'cislo_listku'=>$prijem->doklad_cislo,
                    'spz'=>$prijem->prepravca_spz)) ;?>" target="_blank">Tlačiť</a>
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</div>