<h2 >Príjmy - detail</h2>
<!--<hr>-->
<div class="col-lg-5">
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Detail transakcie <?php echo $this->prijem['doklad_cislo'];?></h3>
    </div>
    <div class="panel-body">




<!--        <div class="col-lg-6">-->
<!--            id-->
<!--            --><?php //echo $this->prijem['ts_prijmy_id']; // render the user name field here ?>
<!--        </div>-->
        <div class="row">
            <fieldset>
                <legend>Dátum príjmu</legend>

                    <div class="col-lg-6">
                        Dátum:
                        <?php echo $this->prijem['datum_prijmu_d']; // render the user name field here ?>
                    </div>
                </fieldset>
        </div>
<!---->
        <div class="row">
            <fieldset>
                <legend>Sklady</legend>
                <div class="col-lg-6">
                    Sklad:
                    <?php echo $this->ciselniky['skladyModel']->getNazov($this->prijem['sklad_enum']); // render the user name field here ?>
                </div>

                <div class="col-lg-6">
                    Podsklad:
                    <?php echo $this->ciselniky['podskladyModel']->getNazov($this->prijem['podsklad_enum']); // render the user name field here ?>
                </div>
            </fieldset>
        </div>

<!--        -->
        <div class="row">
            <fieldset>
                <legend>Dodanie</legend>
        <div class="col-lg-6">
            Dodávateľ:
            <?php echo $this->ciselniky['dodavateliaModel']->getNazov($this->prijem['dodavatel_enum']); // render the user name field here ?>
        </div>

        <div class="col-lg-6">
            Prepravca:
            <?php echo $this->ciselniky['prepravciModel']->getNazov($this->prijem['prepravca_enum']); // render the user name field here ?>
        </div>
        </div>
<!--        -->
        <div class="row">
        <div class="col-lg-6">
            ŠPZ:
            <?php echo $this->prijem['prepravca_spz']; // render the user name field here ?>
        </div>
            </fieldset>
        </div>
<!---->
        <div class="row">
            <fieldset>
                <legend>Množstvo</legend>
                <div class="col-lg-6">
                Netto:
                    <?php echo $this->prijem['q_tony_merane'].'t'; // render the user name field here ?>
                </div>


                <div class="col-lg-6">
                    Nadrozmer:
                    <?php echo $this->prijem['q_tony_nadrozmer'].'t'; // render the user name field here ?>
                </div>

        </div>
        <div class="row">
            <div class="col-lg-6">
                Brutto:
                <?php echo $this->prijem['q_tony_merane_brutto'].'t'; // render the user name field here ?>
            </div>

            <div class="col-lg-6">

                <?php echo $this->prijem['q_prm_merane'].'PRM'; // render the user name field here ?>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-6">
                Tara
                <?php echo $this->prijem['q_tony_merane_tara'].'t'; // render the user name field here ?>
            </div>

                <div class="col-lg-6">

                    <?php echo $this->prijem['q_m3_merane'].'m<sup>3</sup>'; // render the user name field here ?>
                </div>
            </fieldset>
        </div>



    <div class="row">
        <fieldset>
            <legend>Materiál</legend>
        <div class="col-lg-6">
            Typ:
            <?php echo $this->ciselniky['materialyTypyModel']->getNazov($this->prijem['material_typ_enum']); // render the user name field here ?>
        </div>
        <div class="col-lg-6">
            Druh:
            <?php echo $this->ciselniky['materialyDruhyModel']->getNazov($this->prijem['material_druh_enum']); // render the user name field here ?>
        </div>

    </div>


        <div class="row">
            <fieldset>
                <legend>Doplňujúce informácie</legend>
                <div class="col-lg-6">
                    Stav:
                    <?php echo $this->ciselniky['transakcieStavyModel']->getNazov($this->prijem['stav_transakcie']); // render the user name field here ?>
                </div>
                <div class="col-lg-6">
                    Chyba:
                    <?php if ($this->prijem['chyba'] == 1 ) echo 'áno';
                    else echo 'nie'; // render the user name field here ?>
                </div>
        </div>

        <div class="row">

            <div class="col-lg-6">
                Poznámka:
                <?php if ($this->prijem['poznamka'] == '' || $this->prijem['poznamka'] == '0' ) echo 'žiadna poznámka';
                else echo $this->prijem['poznamka']; // render the user name field here ?>
            </div>
            </fieldset>
        </div>



<br>

    <div class="row">


        <div class="col-lg-6 tright">
            <a href="<?php echo $this->url(array('controller'=>'prijmy',
                'action'=>'print',
                'id'=>$this->prijem['ts_prijmy_id'], 'cislo_listku'=>$prijem->doklad_cislo,
                'spz'=>$prijem->prepravca_spz ));?>" target="_blank" class="btn-primary btn" >

              <?php //echo '<img src="'.$this->baseUrl().'/images/tlacit.png" alt="tlacit">'; ?>
                Tlačiť

            </a>

        </div>

        <div class="col-lg-6">
<!--            <dt>&nbsp;</dt>-->
            <a href="<?php echo $this->url(array(
                'controller' => 'prijmy',
                'action' => 'list'
            ), null, true) ?>"  type="button" class="btn btn-warning form-control">Späť</a>
        </div>

    </div>

    </div>
</div>
