<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('wh50k');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <!--  *********** HEAD JS + JQUERY INCLUDES   ******** -->

    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jjquery.js';?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/bootstrap.min.js';?>"></script>

    <!--jquery kamos so zendom-->
    <?php
    echo $this->jQuery()
//    ->setVersion('1.5.1')    // toto nacita najnovsie ENG z netu
//    ->setUiVersion('1.8.11') // toto je k tomu a tiez je to ENG
        ->enable()
        ->uiEnable(); ?>
    <!--jquery-->

    <!-- ostatne JS + jquery pre fancy tables    -->
    <?php

//    $this->inlineScript()->appendFile($this->baseUrl().'/js/raphael.min.js');
//    $this->inlineScript()->appendFile($this->baseUrl().'/js/morris.min.js');
//    $this->inlineScript()->appendFile($this->baseUrl().'/js/morris-data.js');
//    $this->inlineScript()->appendFile($this->baseUrl().'/js/shCore.js');
    $this->inlineScript()->appendFile($this->baseUrl().'/js/jquery.dataTables.min.js');
    echo $this->inlineScript(); ?>

    <!--  *********** KONIEC HEAD JS + JQUERY INCLUDES   ******** -->

<!--   ************ HEAD CSS INCLUDES *****************   -->

    <?php  $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/sb-admin.css'); ?>
	<?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/bootstrap.min.css'); ?>
	<?php  $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/morris.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/font-awesome.min.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/css/jquery.dataTables.css'); ?>
    <?php $this->headLink()
        ->prependStylesheet($this->baseUrl().'/js/jquery/jquery-ui-dark.css'); ?>


	<?php echo $this->headLink(); ?>

<!--    ************** KONIEC CSS INCLUDES ************ -->

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>


    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Navigácia</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'));?>">WH50k</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">

                <li class="dropdown">


                    <?php

                    $notifikacie     = new Application_Model_Notifikacie();


                    $notif_info = $notifikacie->getStatusArray();



                    $count_notif = $notif_info['total'];
                    $prijmy_w = $notif_info['prijmy_waitings'];
                    $prijmy_e = $notif_info['prijmy_errors'];
                    $vydaje_w = $notif_info['vydaje_waitings'];
                    $vydaje_e = $notif_info['vydaje_errors'];
                    $ubytky_ch = $notif_info['ubytky_chyba'];

                    ?>

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                        <?php if ($count_notif > 0)

                        echo '<span id="notif-number">'.$count_notif .'</span>';

                        ?>

                        <i class="fa fa-bell"></i>

                        <b class="caret"></b>
                    </a>



                    <ul class="dropdown-menu alert-dropdown">

                    <?php if ($prijmy_w > 0) { ?>
                        <li>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'prijmy',
                                'action' => 'waitings'
                            ), null, true) ?>">  <span class="label label-warning tleft">Čakajúcich príjmov</span> <span class="notif_count right"> <?php echo $prijmy_w; ?></span> </a>
                        </li>

                    <?php }

                    if ($prijmy_e > 0) { ?>
                        <li>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'prijmy',
                                'action' => 'errors'
                            ), null, true) ?>">  <span class="label label-danger tleft">Chybných príjmov</span> <span class="notif_count right"> <?php echo $prijmy_e; ?> </span></a>
                        </li>
                    <?php }

                    if ($count_notif > 0) {
                    ?>
                        <li class="divider"></li>

                        <?php }

                    if ($vydaje_w >0) {
                    ?>

                        <li>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'vydaje',
                                'action' => 'waitings'
                            ), null, true) ?>"> <span class="label label-warning tleft">Čakajúcich výdajov</span> <span class="notif_count right"> <?php echo $vydaje_w; ?> </span> </a>
                        </li>

                    <?php }

                    if ($vydaje_e > 0 ) {
                        ?>

                        <li>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'vydaje',
                                'action' => 'errors'
                            ), null, true) ?>"> <span class="label label-danger tleft">Chybných výdajov</span> <span class="notif_count right"> <?php echo $vydaje_e; ?> </span>  </a>
                        </li>

                        <?php }

                    if ($ubytky_ch > 0 ) {
                        ?>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'ubytky',
                                'action' => 'list'
                            ), null, true) ?>"> <span class="label label-danger tleft">Chybných úbytkov</span> <span class="notif_count right"> <?php echo $ubytky_ch; ?> </span>  </a>
                        </li>

                    <?php }

                    if ($count_notif >0) {
                        ?>
<!--                        <li>-->
<!--                            <a href="#"> &nbsp;  <span class="label label-primary">taketo mame este farby</span></a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#"> &nbsp; <span class="label label-success">alebo taketo</span></a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#"><span class="label label-info">666 </span> &nbsp;  aj takto sa da </a>-->
<!--                        </li>-->
<!--                        <li class="divider"></li>-->
<!---->
<!--                        <li>-->
                            <a href="#">Celkovo <?php echo $count_notif; ?> notifikácií</a>
                        </li>
                        <?php } ?>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                        <?php
                            $array = (array)$_SESSION[Zend_Auth][storage];
                            echo $array[name];
                        ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a>
                        </li>
                     <!--    <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Správy</a>
                        </li> -->
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Nastavenia</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'));?>"><i class="fa fa-fw fa-power-off"></i> Odhlásiť</a>
                        </li>
                    </ul>
                </li>




            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="<?php echo $this->baseUrl().'/ubytky/list'?>"><i class="fa fa-fw fa-dashboard"></i> Nástenka</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#trans"><i class="fa fa-fw fa-arrows-v"></i> Transakcie <i class="fa fa-fw fa-caret-down"></i></a>
                          
                        
                        <ul id="trans" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl().'/prijmy/list'?>">Príjmy</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/vydaje/list'?>">Výdaje</a>
                            </li>
                            <li>
                                <a href="#">Externá dodávka</a>
                            </li>
                        </ul>


                    </li>
                    <li>
    
                        <a href="javascript:;" data-toggle="collapse" data-target="#administracia"><i class="fa fa-fw fa-edit"></i> Administrácia <i class="fa fa-fw fa-caret-down"></i></a>
                          
                        
                        <ul id="administracia" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl().'/sklady/list'?>">Sklady</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/dodavatelia/list'?>">Dodavatelia</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/odberatelia/list'?>">Odberatelia</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/stroje/list'?>">Stroje</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/materialyDruhy/list'?>">Druhy Materiálov</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/materialyTypy/list'?>">Typy Materiálov</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl().'/prepravci/list'?>">Prepravcovia</a>
                            </li>
<!--                            <li>-->
<!--                                <a href="#">Miesta Štiepenia</a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#">Objednávky Odberateľov</a>-->
<!--                            </li>-->
                        </ul>


                    </li>
                    <li>

                         <a href="javascript:;" data-toggle="collapse" data-target="#prehlady"><i class="fa fa-fw fa-bar-chart-o"></i> Prehľady<i class="fa fa-fw fa-caret-down"></i></a>
                          
                        
                        <ul id="prehlady" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl().'/sklady'?>">Stav Skladov</a>
                            </li>
                            <li>
                                <a href="#">Plnenie Objednávok</a>
                            </li>
                            <li>
                                <a href="#">Vyťaženie Strojov</a>
                            </li>
                        </ul>
                    </li>
                      
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

	    <div id="page-wrapper">

			<div class="container-fluid">

                <div class="row">
                    <div class="col-lg-12">


                          <h1><?php echo $this->escape($this->title); ?></h1>
                            <?php echo $this->layout()->content; ?>

                    </div>
                </div>
                <!-- end of row    -->

			<!-- end of container -->
			</div>


		<!-- end of page-wrapper -->
		</div>


	 <!-- /.end-of-wrapper -->
	</div>




</body>
</html>