<?php
$this->headTitle($this->title);
//definicia farieb skladov - farby sa opakuju v slucke ale ak chces viac roznych treba definovat v css a potom sem nahodit string do pola - automaticky sa to strieba v poradi
$colors = array('1' => 'red', '2' => 'primary', '3' => 'green', '4' => 'yellow', '5' => 'purple', '6' => 'aqua');
//print_r($this->vyvojStavuSkladov);
?>

<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/morris-data.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>







<div class="row">

                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h2>Sklady - aktuálny stav</h2>
                        <hr>
                    </div>

                    <?php
                    $skladyIds = $this->skladyModel->getIds();
                    $counter = 1;
                    ?>

                    <?php foreach ($skladyIds AS $skladId) :
                        if ($counter>count($colors)) {$counter = 1;}
                        ?>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-<?php echo $colors[$counter]?>">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa
                                            /*<?php
                                            if ($this->skladyModel->getMernaJednotka($skladId) <> 1)
                                            {echo "fa-cube";}
                                            else
                                            {echo "fa-database";}
                                            ?>*/ fa-3x">
                                                <?php
                                                    ECHO $this->skladyModel->getSkratka($skladId)

                                            ?></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">
                                            <span style="font-size:26pt;">
                                            <?php
                                                $aktualnyStavSkladu = $this->ubytky->getLastStavSkladu($skladId);
                                                $aktualnyStavSkladu = number_format($aktualnyStavSkladu['t'], 2, ',', ' ');
                                                echo $aktualnyStavSkladu;
                                            ?>
                                            <span style="font-size:10pt;">
                                                t
                                            </span>
                                            </span>
                                        </div>
                                        <div>
                                            <?php
                                                echo $this->skladyModel->getNazov($skladId);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body" style="margin-left: 15px; margin-right: 15px;">


                                    <div class="row">
                                        <table style="border-style: none; width: 100%; font-size: large;">
                                            <tr>
                                                <td>
                                                    <?php
                                                        $aktualnyStavSkladu = $this->ubytky->getLastStavSkladu($skladId);
                                                        $aktualnyStavSkladu = number_format($aktualnyStavSkladu['t'], 2, ',', ' ');
                                                        echo $aktualnyStavSkladu;
                                                    ?>
                                                </td>
                                                <td style="font-weight: bold;">tony</td>
                                            </tr>
                                            <tr>
                                                <td><?php
                                                        $aktualnyStavSkladu = $this->ubytky->getLastStavSkladu($skladId);
                                                        $aktualnyStavSkladu = number_format($aktualnyStavSkladu['prm'], 2, ',', ' ');
                                                        echo $aktualnyStavSkladu;
                                                    ?>
                                                </td>
                                                <td style="font-weight: bold;">PRM</td>

                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php
                                                        $aktualnyStavSkladu = $this->ubytky->getLastStavSkladu($skladId);
                                                        $aktualnyStavSkladu = number_format($aktualnyStavSkladu['m3'], 2, ',', ' ');
                                                        echo $aktualnyStavSkladu;
                                                    ?>
                                                </td>
                                                <td style="font-weight: bold;">m3</td>
                                            </tr>
                                        </table>
                                    </div>






                                <div id="hidden_field<?php echo $counter;?>" class="hhhhidden">
                                    <div class="row">
                                        <hr>
                                    </div>
                                    <div class="row">
                                        <table style="border-style: none; width: 100%">
                                            <tr style="font-weight: bold;">
                                                <td>pohyb</td>
                                                <td>príjmy</td>
                                                <td>výdaje</td>
                                                <td>celkovo</td>
                                            </tr>
                                            <tr>
                                                <td>deň</td>
                                                <td><?php echo $this->pohyby[$skladId]['den']['prijmy'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['den']['vydaje'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['den']['total'];?></td>
                                            </tr>
                                            <tr>
                                                <td>týždeň</td>
                                                <td><?php echo $this->pohyby[$skladId]['tyzden']['prijmy'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['tyzden']['vydaje'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['tyzden']['total'];?></td>
                                            </tr>
                                             <tr>
                                                <td>mesiac</td>
                                                <td><?php echo $this->pohyby[$skladId]['mesiac']['prijmy'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['mesiac']['vydaje'];?></td>
                                                <td><?php echo $this->pohyby[$skladId]['mesiac']['total'];?></td>
                                            </tr>
                                        </table>

                                  </div>

                                        <div class="row">
                                                <hr>
                                        </div>

                                        <div class="row">
                                            <?php
                                                echo "<strong> Data pre graf - last 30 days </strong><br><br>";



                                                foreach ($this->vyvojStavuSkladov[$skladId] AS $stavSkladu)
                                                {
                                                    echo $stavSkladu;
                                                    echo "<br>";
                                                }
                                            ?>

                                            <div id="morris-area-chart-<?php echo $counter; ?>"></div>

                                        </div>
                                </div>






                            </div>

                            <div class="panel-heading center">

                                <button id="button<?php echo $counter;?>" class="btn btn-default" type="button">
                                    <i class="fa fa-bars"></i>
                                </button>

                                <script>

                                    $("#button<?php echo $counter;?>").click( function() {

                                        $("#hidden_field<?php echo $counter;?>").fadeToggle("slide");
                                        $("#hidden_field<?php echo $counter;?>").removeClass("hidden");
                                    });

                                </script>
                            </div>

                        </div>
                    </div>
                    <?php
                    $counter++;
                    endforeach; ?>
    </div>

