<?php
$this->headTitle($this->title);
?>


<div id="".col-lg-12">
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>kód</th>
        <th>sklad</th>
        <th>príjmy</th>
        <th>výdaje</th>
        <th>úbytky</th>
        <th>aktuálny stav</th>
    </tr>


    <?php foreach($this->sklady as $sklad) : ?>
        <tr>
            <td><?php echo $this->escape($sklad->sklady_id);?></td>
            <td><?php echo $this->escape($sklad->kod_skladu);?></td>
            <td><?php echo $this->escape($sklad->nazov_skladu);?></td>
            <td><?php echo $this->prijmy->getSumByColumn('q_tony_merane', 'sklad_enum', $sklad->sklady_id);?></td>
            <td><?php echo $this->vydaje->getSumByColumn('q_tony_merane', 'sklad_enum', $sklad->sklady_id);?></td>
            <td>-</td>
            <td><?php echo ($this->prijmy->getSumByColumn('q_tony_merane', 'sklad_enum', $sklad->sklady_id))-($this->vydaje->getSumByColumn('q_tony_merane', 'sklad_enum', $sklad->sklady_id));?></td>
        </tr>
    <?php endforeach; ?>







</table>
</div>
