<?php
$this->headTitle($this->title);
?>
<p>
    <a href="<?php echo $this->url(array('controller'=>'Miestastiepenia',
        'action'=>'add'));?>">
        <button type="button" class="btn btn-success">Pridať miesto štiepenia</button>
    </a>
</p>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <!--
        <th>ID</th>
        -->
        <th>Názov</th>
        <th>Úpravy</th>
    </tr>


    <?php foreach($this->miestaStiepenia as $miestoStiepenia) : ?>
        <tr>
            <!--
            <td><?php echo $this->escape($miestoStiepenia->miesta_stiepenia_id);?></td>
            -->
            <td><?php echo $this->escape($miestoStiepenia->nazov_miesta);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Miestastiepenia',
                    'action'=>'edit', 'id'=>$miestoStiepenia->miesta_stiepenia_id));?>">Upraviť</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>