<?php
    $this->headTitle($this->title);
?>

<h1><?php echo $this->view->title;?></h1>
<div id="".col-lg-12">
    <table class="table table-striped table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>dátum úbytku</th>
        <th>sklad</th>
        <th>stav ráno</th>
        <th>denný pohyb</th>
        <th>stav večer</th>
        <th>stav celý deň</th>
        <th>úbytok</th>
        <th>konečný stav</th>
        <th>poznámka</th>
    </tr>


    <?php foreach($this->ubytky as $ubytok) : ?>
        <tr>
            <td><?php echo $this->escape($ubytok->ts_ubytky_hmotnosti_id);?></td>
            <td><?php echo $this->escape($ubytok->datum_ubytku_d);?></td>
            <td><?php echo $this->escape($this->sklady->getNazov($ubytok->sklad_enum));?></td>
            <td><?php echo $this->escape($ubytok->q_rano_tony);?></td>
            <td><?php echo $this->escape($ubytok->q_denny_pohyb_tony);?></td>
            <td><?php echo $this->escape($ubytok->q_vecer_tony);?></td>
            <td><?php echo $this->escape($ubytok->q_cely_den_tony);?></td>
            <td><?php echo $this->escape($ubytok->q_ubytok_tony);?></td>
            <td><?php echo $this->escape($ubytok->q_konecny_stav_tony);?></td>
            <td><?php echo $this->escape($ubytok->poznamka);?></td>

        </tr>
    <?php endforeach; ?>
    </table>
    <hr>
    <?php
        echo $this->prijmy->getSumByColumnBetween('q_tony_merane', 'datum_prijmu_d', '2015-06-01', '2015-06-02', 'sklad_enum', 3);
    ?>
</div>