<?php
    $this->headTitle($this->title);
//    print_r($this->ubytkyModel->getLastXValuesForAllWHs(2));
?>

<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>


<a href="<?php echo $this->url(array('controller'=>'ubytky',
            'action'=>'refreshData'));?>"><button type="button" class="btn btn-success">Prepočítať tabuľku</button></a>
<br><br>

<div id="morris-area-chart"></div>

<?php
    $status = $this->notifikacieModel->getStatusArray();
    if ($status['ubytky_chyba'] > 0) {?>
      <div class="alert alert-danger alert-dismissable">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
             <i class="fa fa-warning"></i> Červenou farbou sú označené dni s <strong>neplatým denným pohybom.</strong>.
        </div>
    <?php }
?>

<!--Taby-->
<ul class="nav nav-tabs">
    <?php
    foreach($this->sklady->getIds() as $skladId):?>
    <li <?php if ($skladId == 1){echo "class=\"active\"";}?>><a data-toggle="tab" href="#menu<?php echo $skladId;?>"><?php echo $this->sklady->getNazov($skladId);?></a></li>
    <?php endforeach; ?>
</ul>

<div class="tab-content">
    <?php
    foreach($this->sklady->getIds() as $skladId):?>
        <div id="<?php echo "menu".$skladId;?>" <?php if ($skladId == 1){echo "class=\"tab-pane fade in active\"";} else { echo "class=\"tab-pane fade\"";}?>>
            <div id="" class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                <tr>
                    <!--
                    <th>ID</th>
                    -->
                    <th>Dátum</th>
                    <th>Sklad</th>
                    <th>Ráno</th>
                    <th>Pohyb</th>
                    <th>Večer</th>
                    <th>Stav</th>
                    <th>Úbytok</th>
                    <th>Konečný Stav</th>
                    <th>Poznámka</th>
                    <th>MJ</th>
                </tr>


                <?php foreach($this->ubytkyVPoli[$skladId] as $ubytok) : ?>
                    <tr
                        <?php
                            if (strpos($ubytok->poznamka, 'Nedostatok na sklade.') !== FALSE){
                                echo "class='danger'";
                            }
                        ?>
                        >
                        <!--
                        <td><?php echo $this->escape($ubytok->ts_ubytky_hmotnosti_id);?></td>
                        -->
                        <td><?php echo date("d.m.Y", strtotime($this->escape($ubytok->datum_ubytku_d)));?></td>
                        <td><?php echo $this->escape($this->sklady->getSkratka($ubytok->sklad_enum));?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_rano_tony), 4, ",", " ");?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_denny_pohyb_tony), 4, ",", " ");?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_vecer_tony), 4, ",", " ");?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_cely_den_tony), 4, ",", " ");?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_ubytok_tony), 4, ",", " ");?></td>
                        <td><?php echo number_format($this->escape($ubytok->q_konecny_stav_tony), 4, ",", " ");?></td>
                        <td><?php echo $this->escape($ubytok->poznamka);?></td>
                        <td><?php echo $this->escape($this->sklady->getMernaJednotkaSkratka($ubytok->merna_jednotka_enum));?></td>
                    </tr>
                <?php endforeach; ?>
                </table>
            </div>

        </div>
    <?php endforeach; ?>

</div>

<script>
    Morris.Area({
        element: 'morris-area-chart',
        data: <?php echo json_encode($this->ubytkyModel->getLastXValuesForAllWHs(365)); ?>,
        xkey: 'datum',
        ykeys: ['sklad1', 'sklad2', 'sklad3', 'sklad4'],
        labels: ['Zvolen', 'Hronská Breznica', 'Prešov', 'Kráľova Lehota'],
        pointSize: 2,
        hideHover: 'auto',
        resize: true
    });



</script>
