<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
$prijmy = new Application_Model_DbTable_Prijmy();
?>


<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#fancy_table').DataTable( {
            "order": [[ 1, "desc" ]],
            columnDefs: [
                { "sType": "title-string", "aTargets": [ 3 ]  }
//                    { "sType": "alt-string", "aTargets" : 11 }
            ],
            initComplete: function () {
                var api = this.api();
                var abc = 0;
                api.columns().indexes().flatten().each( function ( i ) {
                    var column = api.column( i );
                    if (i != abc) {
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.DataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    }
                } );
            }
        } );
    } );
</script>


<p>
    <a href="<?php echo $this->url(array('controller'=>'Objednavky',
        'action'=>'add'));?>">
        <button type="button" class="btn btn-success">Pridať objednávku</button>
    </a>
</p>

<?php if ($this->objednavkyModel->getCountNekompatibilneObjednavky() > 0) {?>
        <div class="alert alert-danger alert-dismissable">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
             <i class="fa fa-warning"></i> Definujte správnu <strong>MERNÚ JEDNOTKU</strong> objednávky! Žlté objednávky nemajú MJ zhodnú s MJ zákazníka.
        </div>
    <?php ;}?>

<div id=".col-lg-12"  class="table-responsive">
<table id="fancy_table"  class="table table-striped table-hover">


    <thead>
    <tr class="tableizer-firsrow">
<!--        <th>ID</th>-->
        <th>Detail</th>
        <th>Rok</th>
        <th>Mesiac</th>
        <th>Zákazník</th>
        <th>Množstvo</th>
        <th>Výdaje</th>
        <th>xVýroba</th>
        <th>xDodávka</th>
        <th>Na dodanie</th>
        <th>MJ</th>
        <th>Úpravy</th>
    </tr>
    </thead>

    <tfoot>
    <tr>
<!--        <th></th>-->
        <th>    </th>
        <th></th>

        <th>mesiac</th>
        <th>zákazník</th>
        <th>množstvo</th>
        <th>výdaje</th>
        <th>xvýroba</th>
        <th>xdodávka</th>
        <th>na dodanie</th>
        <th>MJ</th>

    </tr>
    </tfoot>

    <tbody>
    <?php foreach($this->objednavky as $objednavka) : ?>
    <?php
            $nekompatibilneTypyMJ = false;
            if ($this->zakazniciModel->getMernaJednotka($objednavka->zakaznik_enum) <> $objednavka->merna_jednotka_enum){
                $nekompatibilneTypyMJ = true;
            }
        ?>
        <tr <?php if ($nekompatibilneTypyMJ){ echo "style=\"background-color:#FFFF99;\"";}?> >
<!--            <td>--><?php //echo $this->escape($objednavka->objednavky_id);?><!--</td>-->
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Objednavky',
                    'action'=>'preview', 'id'=>$objednavka->objednavky_id));?>"> <i class="fa fa-eye"></i></a>
            </td>
            <td><?php echo $this->escape($this->rokyModel->getNazov($objednavka->rok_enum));?></td>
            <td><?php echo $this->escape($this->mesiaceModel->getNazov($objednavka->mesiac_enum));?></td>

            <td><?php echo $this->escape($this->zakazniciModel->getNazov($objednavka->zakaznik_enum));?></td>
            <td><?php echo number_format($this->escape($objednavka->mnozstvo), 2, ",", " ");?></td>

            <?php $vydaje = $this->vydajeModel->getSubmittedQuantityByStockYearMonth($objednavka->merna_jednotka_enum,$objednavka->zakaznik_enum,$objednavka->rok_enum,$objednavka->mesiac_enum);?>
            <?php $xvyroby = $this->xvyrobyModel->getSubmittedQuantityByStockYearMonth($objednavka->merna_jednotka_enum,$objednavka->zakaznik_enum,$objednavka->rok_enum,$objednavka->mesiac_enum);?>
            <?php $xdodavky = $this->xdodavkyModel->getSubmittedQuantityByStockYearMonth($objednavka->merna_jednotka_enum,$objednavka->zakaznik_enum,$objednavka->rok_enum,$objednavka->mesiac_enum);?>
            <td><?php echo number_format($vydaje, 2, ",", " ");?></td>
            <td><?php echo number_format($xvyroby, 2, ",", " ");?></td>
            <td><?php echo number_format($xdodavky, 2, ",", " ");?></td>
            <td><?php echo number_format($objednavka->mnozstvo - $vydaje - $xvyroby - $xdodavky, 2, ",", " ")?></td>

            <td><?php echo $this->escape($this->merneJednotkyModel->getSkratka($objednavka->merna_jednotka_enum));?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'Objednavky',
                    'action'=>'edit', 'id'=>$objednavka->objednavky_id));?>"> <i class="fa fa-pencil-square-o"></i></a>
                <a href="<?php echo $this->url(array('controller'=>'Objednavky',
                    'action'=>'delete', 'id'=>$objednavka->objednavky_id));?>"> <i class="fa fa-trash-o"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>