<?php
$this->title = "Upraviť zákazníka";
$this->headTitle($this->title);
//echo $this->form ;
?>




<div class="col-lg-5">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Detail transakcie </h3>
        </div>
        <div class="panel-body">
            <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                  method="<?php echo $this->escape($this->form->getMethod()) ?>"
                  enctype="multipart/form-data" class="normal">

                <?php echo $this->form->zakaznici_id; ?>

                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->interny_kod;?>
                        </div>
                    </fieldset>
                </div>

                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->meno;?>
                        </div>
                    </fieldset>
                </div>


                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->nazov_spolocnosti; ?>
                        </div>
                    </fieldset>
                </div>

                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->ico;?>
                        </div>
                    </fieldset>
                </div>

                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->ic_dph;?>
                        </div>
                    </fieldset>
                </div>

                <div class="row">
                    <fieldset>
                        <div class="col-lg-12">

                            <?php echo $this->form->adresa;?>
                        </div>
                    </fieldset>
                </div>


                <div class="row">
                    <fieldset>
                        <div class="col-lg-6">

                            <?php echo $this->form->merna_jednotka_enum; ?>
                        </div>
                    </fieldset>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $this->form->submit;  ?>
                    </div>


                    <div class="col-lg-6">
                        <dt>&nbsp;</dt>
                        <a href="<?php
                        //    pageManager
                        echo $this->url(array(
                            'controller' => 'zakaznici',
                            'action' => 'list'
                        ), null, true) ?>"  type="button" class="btn btn-warning">Späť</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>