<?php
$this->headTitle($this->title);
$zakazniciModel = $this->zakazniciModel;
//print_r($this->dodaneMnozstvoZakaznikom);
?>


<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>zákazník</th>
        <th>dodané množstvo</th>
    </tr>

<?php foreach($this->dodaneMnozstvoZakaznikom as $zakaznik) : ?>
        <tr>
            <td><?php echo $this->escape($zakazniciModel->getNazov($zakaznik['id']));?></td>
            <td><?php echo number_format($this->escape($zakaznik['q_tony_merane']),2, ",", " "). " t";?></td>


        </tr>
    <?php endforeach; ?>

</table>