<?php
$this->headTitle($this->title);
$zakazniciModel = $this->zakazniciModel;

?>


<script src="<?php echo $this->baseUrl().'/js/morris.min.js';?>"></script>
<script src="<?php echo $this->baseUrl().'/js/raphael.min.js';?>"></script>

<div class="row">


    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Zakaznik</th>
            <th>počet dodávok</th>

        </tr>


        <?php foreach($this->zakazniciModel->getIds() as $zakaznikId) : ?>
            <tr>
                <td><?php echo $this->zakazniciModel->getNazov($zakaznikId);?></td>
                <td><?php echo $this->zakazniciModel->getCountTransactionsByStrojId($zakaznikId);?></td>
            </tr>
        <?php endforeach; ?>

    </table>
</div>


<div class="row">
    <div class="col-lg-12">
        <div id="pie-chart"></div>
    </div>
</div>

<script>

    Morris.Donut({
        element: 'pie-chart',
        data: [ <?php $counter = 0;
    foreach($this->zakazniciModel->getIds() as $zakaznikId) : ?>
            { label: <?php echo '"'.$this->zakazniciModel->getNazov($zakaznikId).'"';?>, value: <?php echo $this->zakazniciModel->getCountTransactionsByStrojId($zakaznikId); ?> } <?php $counter++; if ($counter < count($this->zakazniciModel->getIds()) ) echo ','; ?>
            <?php endforeach; ?>
        ]

    });

</script>


